### ISSUE TITLE
RuntimeError: NCCL error: unhandled cuda error in vLLM backend with two GPUs

### ISSUE THREAD

**Issue by zhyim0712** [gpustack/gpustack#1263]
Error log
```Shell
`2025-02-19T19:18:08+08:00 - gpustack.worker.backends.vllm - INFO - Starting vllm server
INFO 02-19 19:18:13 __init__.py:190] Automatically detected platform cuda.
INFO 02-19 19:18:14 api_server.py:840] vLLM API server version 0.7.2
INFO 02-19 19:18:14 api_server.py:841] args: Namespace(subparser='serve', model_tag='/models/dsr1-70b', config='', host='0.0.0.0', port=40281, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, enable_reasoning=False, reasoning_parser=None, tool_call_parser=None, tool_parser_plugin='', model='/models/dsr1-70b', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=8192, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['dsr1-70b'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function serve at 0x7b601bd33250>)
INFO 02-19 19:18:14 api_server.py:206] Started engine process with PID 1698897
INFO 02-19 19:18:19 __init__.py:190] Automatically detected platform cuda.
INFO 02-19 19:18:21 config.py:542] This model supports multiple tasks: {'generate', 'score', 'embed', 'reward', 'classify'}. Defaulting to 'generate'.
INFO 02-19 19:18:21 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-19 19:18:28 config.py:542] This model supports multiple tasks: {'generate', 'embed', 'reward', 'classify', 'score'}. Defaulting to 'generate'.
INFO 02-19 19:18:28 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-19 19:18:28 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/models/dsr1-70b', speculative_config=None, tokenizer='/models/dsr1-70b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=dsr1-70b, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True, 
WARNING 02-19 19:18:29 multiproc_worker_utils.py:300] Reducing Torch parallelism from 96 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 02-19 19:18:29 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-19 19:18:30 cuda.py:230] Using Flash Attention backend.
INFO 02-19 19:18:34 __init__.py:190] Automatically detected platform cuda.
INFO 02-19 19:18:34 __init__.py:190] Automatically detected platform cuda.
INFO 02-19 19:18:34 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=1699361) INFO 02-19 19:18:35 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=1699362) INFO 02-19 19:18:36 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=1699360) INFO 02-19 19:18:36 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=1699362) INFO 02-19 19:18:37 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=1699361) INFO 02-19 19:18:37 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=1699360) INFO 02-19 19:18:37 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=1699361) INFO 02-19 19:18:39 utils.py:950] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=1699360) INFO 02-19 19:18:39 utils.py:950] Found nccl from library libnccl.so.2
INFO 02-19 19:18:39 utils.py:950] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=1699362) INFO 02-19 19:18:39 utils.py:950] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=1699361) INFO 02-19 19:18:39 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=1699362) INFO 02-19 19:18:39 pynccl.py:69] vLLM is using nccl==2.21.5
INFO 02-19 19:18:39 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=1699360) INFO 02-19 19:18:39 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method init_device.
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] Traceback (most recent call last):
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 2220, in run_method
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 166, in init_device
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     init_worker_distributed_environment(self.vllm_config, self.rank,
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 506, in init_worker_distributed_environment
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1103, in ensure_model_parallel_initialized
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     initialize_model_parallel(tensor_model_parallel_size,
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1047, in initialize_model_parallel
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     _TP = init_model_parallel_group(group_ranks,
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 876, in init_model_parallel_group
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     return GroupCoordinator(
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 218, in __init__
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.pynccl_comm = PyNcclCommunicator(
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorkerProcess pid=1699362) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] RuntimeError: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method init_device.
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] Traceback (most recent call last):
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 2220, in run_method
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 166, in init_device
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     init_worker_distributed_environment(self.vllm_config, self.rank,
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 506, in init_worker_distributed_environment
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1103, in ensure_model_parallel_initialized
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     initialize_model_parallel(tensor_model_parallel_size,
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1047, in initialize_model_parallel
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     _TP = init_model_parallel_group(group_ranks,
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 876, in init_model_parallel_group
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     return GroupCoordinator(
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 218, in __init__
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.pynccl_comm = PyNcclCommunicator(
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorkerProcess pid=1699361) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] RuntimeError: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
ERROR 02-19 19:18:42 engine.py:389] NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
ERROR 02-19 19:18:42 engine.py:389] Traceback (most recent call last):
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 380, in run_mp_engine
ERROR 02-19 19:18:42 engine.py:389]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 123, in from_engine_args
ERROR 02-19 19:18:42 engine.py:389]     return cls(ipc_path=ipc_path,
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 75, in __init__
ERROR 02-19 19:18:42 engine.py:389]     self.engine = LLMEngine(*args, **kwargs)
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 273, in __init__
ERROR 02-19 19:18:42 engine.py:389]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 262, in __init__
ERROR 02-19 19:18:42 engine.py:389]     super().__init__(*args, **kwargs)
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 51, in __init__
ERROR 02-19 19:18:42 engine.py:389]     self._init_executor()
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/mp_distributed_executor.py", line 124, in _init_executor
ERROR 02-19 19:18:42 engine.py:389]     self._run_workers("init_device")
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/mp_distributed_executor.py", line 185, in _run_workers
ERROR 02-19 19:18:42 engine.py:389]     driver_worker_output = run_method(self.driver_worker, sent_method,
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 2220, in run_method
ERROR 02-19 19:18:42 engine.py:389]     return func(*args, **kwargs)
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 166, in init_device
ERROR 02-19 19:18:42 engine.py:389]     init_worker_distributed_environment(self.vllm_config, self.rank,
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 506, in init_worker_distributed_environment
ERROR 02-19 19:18:42 engine.py:389]     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1103, in ensure_model_parallel_initialized
ERROR 02-19 19:18:42 engine.py:389]     initialize_model_parallel(tensor_model_parallel_size,
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1047, in initialize_model_parallel
ERROR 02-19 19:18:42 engine.py:389]     _TP = init_model_parallel_group(group_ranks,
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 876, in init_model_parallel_group
ERROR 02-19 19:18:42 engine.py:389]     return GroupCoordinator(
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 218, in __init__
ERROR 02-19 19:18:42 engine.py:389]     self.pynccl_comm = PyNcclCommunicator(
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
ERROR 02-19 19:18:42 engine.py:389]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
ERROR 02-19 19:18:42 engine.py:389]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
ERROR 02-19 19:18:42 engine.py:389]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
ERROR 02-19 19:18:42 engine.py:389]     raise RuntimeError(f"NCCL error: {error_str}")
ERROR 02-19 19:18:42 engine.py:389] RuntimeError: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method init_device.
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] Traceback (most recent call last):
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 2220, in run_method
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 166, in init_device
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     init_worker_distributed_environment(self.vllm_config, self.rank,
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 506, in init_worker_distributed_environment
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1103, in ensure_model_parallel_initialized
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     initialize_model_parallel(tensor_model_parallel_size,
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1047, in initialize_model_parallel
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     _TP = init_model_parallel_group(group_ranks,
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 876, in init_model_parallel_group
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     return GroupCoordinator(
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 218, in __init__
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.pynccl_comm = PyNcclCommunicator(
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorkerProcess pid=1699360) ERROR 02-19 19:18:42 multiproc_worker_utils.py:242] RuntimeError: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
Traceback (most recent call last):
  File "/usr/local/bin/vllm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/vllm/scripts.py", line 204, in main
    args.dispatch_function(args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/scripts.py", line 44, in serve
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 875, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 136, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 230, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.`
```

**Comment by zhyim0712** [comment]
系统版本Linux Supermicro-GPU-Server-SYS-821GE-TNHR-DC2-Y10-1U 6.5.0-44-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
宿主机驱动

<img width="548" alt="Image" src="https://github.com/user-attachments/assets/30b61aec-6ce0-465f-be6f-27d6811916c3" />
宿主机没有安装libnccl2和libnccl-dev
docker启动命令
`gpustack:
    container_name: gpustack
    image: g-12138-docker.pkg.coding.net/docker/image/gpustack:latest
    shm_size: 512g
    volumes:
      - ./volumes/gpustack:/var/lib/gpustack
      - /home/models:/models
    ipc: host
    ports:
      - 2999:80
    environment:
      TZ: Asia/Shanghai
      VLLM_ALLOW_LONG_MAX_MODEL_LEN: 1
      GPUSTACK_DATABASE_URL: postgresql://postgres:postgres@pgvector:5432/postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["all"]
              capabilities: [gpu]
    restart: always`

**Comment by pengjiang80** [comment]
It may be related to the env configuration. Does it work if you run the https://github.com/vllm-project/vllm/blob/main/collect_env.py script?

**Comment by zhyim0712** [comment]
驱动更新到550就好了
