### ISSUE TITLE
Failed to run llama-box with RTX-5090D - CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by youkai1981** [gpustack/gpustack#1382]
在ubuntu中部署也同样会报错

2025-03-01T19:05:49+08:00 - gpustack.worker.backends.llama_box - INFO - Starting llama-box server
0.00.001.672 I 
0.00.001.686 I arguments  : C:\Users\youkai\pipx\venvs\gpustack\Lib\site-packages\gpustack\third_party\bin\llama-box\llama-box.exe --host 0.0.0.0 --embeddings --gpu-layers 2 --parallel 4 --ctx-size 8192 --port 40189 --model C:\AIModel\lmstudio-community\DeepSeek-R1\DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf --alias DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf --no-mmap --no-warmup
0.00.001.687 I version    : v0.0.117 (315b735)
0.00.001.687 I compiler   : unknown
0.00.001.688 I target     : unknown
0.00.001.689 I vendor     : llama.cpp 27d135c9 (4598), stable-diffusion.cpp 102953d (203)
0.00.023.114 I ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
0.00.023.119 I ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
0.00.023.119 I ggml_cuda_init: found 1 CUDA devices:
0.00.023.126 I   Device 0: NVIDIA GeForce RTX 5090 D, compute capability 12.0, VMM: yes
0.00.024.211 I system_info: n_threads = 12 (n_threads_batch = 12) / 20 | CUDA : ARCHS = 600,610,700,750,800,860,890,900 | F16 = 1 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | 
0.00.024.213 I 
0.00.024.746 I srv                      main: listening, hostname = 0.0.0.0, port = 40189, n_threads = 6 + 2
0.00.025.925 I srv                      main: loading model
0.00.025.928 I srv                load_model: loading model 'C:\AIModel\lmstudio-community\DeepSeek-R1\DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf'
0.00.085.169 I llama_model_load_from_file_impl: using device CUDA0 (NVIDIA GeForce RTX 5090 D) - 30843 MiB free
0.00.113.703 I llama_model_loader: loaded meta data with 26 key-value pairs and 339 tensors from C:\AIModel\lmstudio-community\DeepSeek-R1\DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf (version GGUF V3 (latest))
0.00.113.715 I llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
0.00.113.718 I llama_model_loader: - kv   0:                       general.architecture str              = qwen2
0.00.113.719 I llama_model_loader: - kv   1:                               general.type str              = model
0.00.113.719 I llama_model_loader: - kv   2:                               general.name str              = DeepSeek R1 Distill Qwen 7B
0.00.113.720 I llama_model_loader: - kv   3:                           general.basename str              = DeepSeek-R1-Distill-Qwen
0.00.113.721 I llama_model_loader: - kv   4:                         general.size_label str              = 7B
0.00.113.722 I llama_model_loader: - kv   5:                          qwen2.block_count u32              = 28
0.00.113.722 I llama_model_loader: - kv   6:                       qwen2.context_length u32              = 131072
0.00.113.723 I llama_model_loader: - kv   7:                     qwen2.embedding_length u32              = 3584
0.00.113.723 I llama_model_loader: - kv   8:                  qwen2.feed_forward_length u32              = 18944
0.00.113.724 I llama_model_loader: - kv   9:                 qwen2.attention.head_count u32              = 28
0.00.113.724 I llama_model_loader: - kv  10:              qwen2.attention.head_count_kv u32              = 4
0.00.113.736 I llama_model_loader: - kv  11:                       qwen2.rope.freq_base f32              = 10000.000000
0.00.113.738 I llama_model_loader: - kv  12:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
0.00.113.738 I llama_model_loader: - kv  13:                          general.file_type u32              = 15
0.00.113.739 I llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = gpt2
0.00.113.739 I llama_model_loader: - kv  15:                         tokenizer.ggml.pre str              = qwen2
0.00.137.451 I llama_model_loader: - kv  16:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
0.00.148.055 I llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
0.00.173.756 I llama_model_loader: - kv  18:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
0.00.173.763 I llama_model_loader: - kv  19:                tokenizer.ggml.bos_token_id u32              = 151646
0.00.173.764 I llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151643
0.00.173.764 I llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
0.00.173.766 I llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
0.00.173.767 I llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
0.00.173.771 I llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {% if not add_generation_prompt is de...
0.00.173.771 I llama_model_loader: - kv  25:               general.quantization_version u32              = 2
0.00.173.772 I llama_model_loader: - type  f32:  141 tensors
0.00.173.772 I llama_model_loader: - type q4_K:  169 tensors
0.00.173.773 I llama_model_loader: - type q6_K:   29 tensors
0.00.173.774 I print_info: file format = GGUF V3 (latest)
0.00.173.775 I print_info: file type   = Q4_K - Medium
0.00.173.784 I print_info: file size   = 4.36 GiB (4.91 BPW) 
0.00.237.938 W load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
0.00.238.121 I load: special tokens cache size = 22
0.00.257.619 I load: token to piece cache size = 0.9310 MB
0.00.257.632 I print_info: arch             = qwen2
0.00.257.632 I print_info: vocab_only       = 0
0.00.257.632 I print_info: n_ctx_train      = 131072
0.00.257.633 I print_info: n_embd           = 3584
0.00.257.633 I print_info: n_layer          = 28
0.00.257.642 I print_info: n_head           = 28
0.00.257.644 I print_info: n_head_kv        = 4
0.00.257.644 I print_info: n_rot            = 128
0.00.257.645 I print_info: n_swa            = 0
0.00.257.645 I print_info: n_embd_head_k    = 128
0.00.257.645 I print_info: n_embd_head_v    = 128
0.00.257.646 I print_info: n_gqa            = 7
0.00.257.648 I print_info: n_embd_k_gqa     = 512
0.00.257.649 I print_info: n_embd_v_gqa     = 512
0.00.257.651 I print_info: f_norm_eps       = 0.0e+00
0.00.257.656 I print_info: f_norm_rms_eps   = 1.0e-06
0.00.257.656 I print_info: f_clamp_kqv      = 0.0e+00
0.00.257.657 I print_info: f_max_alibi_bias = 0.0e+00
0.00.257.657 I print_info: f_logit_scale    = 0.0e+00
0.00.257.658 I print_info: n_ff             = 18944
0.00.257.659 I print_info: n_expert         = 0
0.00.257.659 I print_info: n_expert_used    = 0
0.00.257.659 I print_info: causal attn      = 1
0.00.257.659 I print_info: pooling type     = 0
0.00.257.659 I print_info: rope type        = 2
0.00.257.660 I print_info: rope scaling     = linear
0.00.257.660 I print_info: freq_base_train  = 10000.0
0.00.257.662 I print_info: freq_scale_train = 1
0.00.257.663 I print_info: n_ctx_orig_yarn  = 131072
0.00.257.663 I print_info: rope_finetuned   = unknown
0.00.257.663 I print_info: ssm_d_conv       = 0
0.00.257.663 I print_info: ssm_d_inner      = 0
0.00.257.663 I print_info: ssm_d_state      = 0
0.00.257.664 I print_info: ssm_dt_rank      = 0
0.00.257.664 I print_info: ssm_dt_b_c_rms   = 0
0.00.257.664 I print_info: model type       = 7B
0.00.257.665 I print_info: model params     = 7.62 B
0.00.257.666 I print_info: general.name     = DeepSeek R1 Distill Qwen 7B
0.00.257.667 I print_info: vocab type       = BPE
0.00.257.667 I print_info: n_vocab          = 152064
0.00.257.667 I print_info: n_merges         = 151387
0.00.257.668 I print_info: BOS token        = 151646 '<｜begin▁of▁sentence｜>'
0.00.257.668 I print_info: EOS token        = 151643 '<｜end▁of▁sentence｜>'
0.00.257.668 I print_info: EOT token        = 151643 '<｜end▁of▁sentence｜>'
0.00.257.668 I print_info: PAD token        = 151643 '<｜end▁of▁sentence｜>'
0.00.257.669 I print_info: LF token         = 198 'Ċ'
0.00.257.669 I print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
0.00.257.670 I print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
0.00.257.670 I print_info: FIM MID token    = 151660 '<|fim_middle|>'
0.00.257.670 I print_info: FIM PAD token    = 151662 '<|fim_pad|>'
0.00.257.671 I print_info: FIM REP token    = 151663 '<|repo_name|>'
0.00.257.672 I print_info: FIM SEP token    = 151664 '<|file_sep|>'
0.00.257.672 I print_info: EOG token        = 151643 '<｜end▁of▁sentence｜>'
0.00.257.673 I print_info: EOG token        = 151662 '<|fim_pad|>'
0.00.257.673 I print_info: EOG token        = 151663 '<|repo_name|>'
0.00.257.673 I print_info: EOG token        = 151664 '<|file_sep|>'
0.00.257.673 I print_info: max token length = 256
0.00.707.759 I load_tensors: offloading 2 repeating layers to GPU
0.00.707.766 I load_tensors: offloaded 2/29 layers to GPU
0.00.707.769 I load_tensors:    CUDA_Host model buffer size =  3883.68 MiB
0.00.707.771 I load_tensors:          CPU model buffer size =   292.36 MiB
0.00.707.772 I load_tensors:        CUDA0 model buffer size =   284.41 MiB
0.01.039.666 I srv       log_server_response: rid  | GET /v1/models 127.0.0.1:53918 | status 503 | cost 1.01s
0.02.279.936 I llama_init_from_model: n_seq_max     = 4
0.02.279.940 I llama_init_from_model: n_ctx         = 8192
0.02.279.941 I llama_init_from_model: n_ctx_per_seq = 2048
0.02.279.941 I llama_init_from_model: n_batch       = 2048
0.02.279.941 I llama_init_from_model: n_ubatch      = 512
0.02.279.942 I llama_init_from_model: flash_attn    = 0
0.02.279.945 I llama_init_from_model: freq_base     = 10000.0
0.02.279.946 I llama_init_from_model: freq_scale    = 1
0.02.279.947 W llama_init_from_model: n_ctx_per_seq (2048) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
0.02.279.954 I llama_kv_cache_init: kv_size = 8192, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 28, can_shift = 1
0.02.344.700 I llama_kv_cache_init:        CPU KV buffer size =   416.00 MiB
0.02.345.994 I llama_kv_cache_init:      CUDA0 KV buffer size =    32.00 MiB
0.02.346.000 I llama_init_from_model: KV self size  =  448.00 MiB, K (f16):  224.00 MiB, V (f16):  224.00 MiB
0.02.346.010 I llama_init_from_model:        CPU  output buffer size =     0.05 MiB
0.02.352.430 I llama_init_from_model:      CUDA0 compute buffer size =   730.36 MiB
0.02.352.436 I llama_init_from_model:  CUDA_Host compute buffer size =    23.01 MiB
0.02.352.436 I llama_init_from_model: graph nodes  = 986
0.02.352.438 I llama_init_from_model: graph splits = 368 (with bs=512), 3 (with bs=1)
0.02.352.441 I common_init_from_params: setting dry_penalty_last_n to ctx_size = 8192
0.02.352.444 I srv                load_model: prompt caching enabled
0.02.358.506 I srv                load_model: chat template, built_in: true, alias: deepseek3, tool call: unsupported, example:
You are a helpful assistant
<｜User｜>Hello<｜Assistant｜>Hi there<｜end▁of▁sentence｜><｜User｜>How are you?<｜Assistant｜>
0.02.358.509 I srv                      main: initializing server
0.02.358.510 I srv                      init: initializing slots, n_slots = 4
0.02.358.620 I srv                      main: starting server
0.04.082.226 I srv        log_server_request: rid 4056286 | GET /v1/models 127.0.0.1:53923
0.04.082.315 I srv       log_server_response: rid 4056286 | GET /v1/models 127.0.0.1:53923 | status 200 | cost 0.00s
0.04.466.952 I srv        log_server_request: rid 4441010 | GET /v1/models 192.168.0.172:53924
0.04.467.048 I srv       log_server_response: rid 4441010 | GET /v1/models 192.168.0.172:53924 | status 200 | cost 0.00s
0.17.365.320 I srv        log_server_request: rid 17339378 | POST /v1/chat/completions 192.168.0.172:53941
0.17.365.822 I srv oaicompat_completions_req: rid 17339378 | {"messages":"[...]","seed":null,"stop":null,"temperature":1,"top_p":1,"max_tokens":1024,"model":"DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf","stream":true,"stream_options":{"include_usage":true}}
0.17.512.622 E ggml_cuda_compute_forward: ADD failed
D:\a\llama-box\llama-box\llama.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:72: CUDA error
0.17.512.848 E CUDA error: no kernel image is available for execution on the device
0.17.512.858 E   current device: 0, in function ggml_cuda_compute_forward at D:\a\llama-box\llama-box\llama.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:2313
0.17.512.858 E   err

**Comment by youkai1981** [comment]
补充说明
D:\a\llama-box\llama-box\llama.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:2313
这个路径我的电脑上并不存在

**Comment by youkai1981** [comment]
补充在ubuntu中运行也存在类似问题，只不过路径变化了，同样本机也不存在/home/runner/work/llama-box/这样的路径

<｜User｜>Hello<｜Assistant｜>Hi there<｜end▁of▁sentence｜><｜User｜>How are you?<｜Assistant｜>
0.17.998.499 I srv                      main: initializing server
0.17.998.501 I srv                      init: initializing slots, n_slots = 4
0.17.998.710 I srv                      main: starting server
0.19.201.186 I srv        log_server_request: rid 21092324147 | GET /v1/models 127.0.0.1:63304
0.19.201.342 I srv       log_server_response: rid 21092324147 | GET /v1/models 127.0.0.1:63304 | status 200 | cost 0.00s
0.19.293.906 I srv        log_server_request: rid 21092416865 | GET /v1/models 192.168.5.165:56482
0.19.294.102 I srv       log_server_response: rid 21092416865 | GET /v1/models 192.168.5.165:56482 | status 200 | cost 0.00s
1.11.277.868 I srv        log_server_request: rid 21144400826 | POST /v1/chat/completions 192.168.5.165:43464
1.11.278.146 I srv oaicompat_completions_req: rid 21144400826 | {"messages":"[...]","seed":null,"stop":null,"temperature":1,"top_p":1,"max_tokens":4096,"model":"deepseek-r1","stream":true,"stream_options":{"include_usage":true}}
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:72: 1.11.287.297 E ggml_cuda_compute_forward: RMS_NORM failed
CUDA error
1.11.287.313 E CUDA error: no kernel image is available for execution on the device
1.11.287.317 E   current device: 0, in function ggml_cuda_compute_forward at /home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2313
1.11.287.318 E   err

**Comment by pengjiang80** [comment]
Which CUDA version are you using? RTX-5090 is SM_120 which requires the latest CUDA 12.8.

**Comment by pengjiang80** [comment]
@thxCode Do we need to build llama-box with cuda 12.8 to support this?

**Comment by youkai1981** [comment]
Driver Version: 572.60         CUDA Version: 12.8

**Comment by youkai1981** [comment]
Driver Version: 572.60
CUDA Version: 12.8

![Image](https://github.com/user-attachments/assets/fdd04ff6-4732-4e46-b747-be7da71e9b16)


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Jan_15_19:38:46_Pacific_Standard_Time_2025
Cuda compilation tools, release 12.8, V12.8.61
Build cuda_12.8.r12.8/compiler.35404655_0

![Image](https://github.com/user-attachments/assets/6d076aa0-9f05-4984-b85b-85f804855948)

**Comment by youkai1981** [comment]
即便我把显卡换为telsa m40依然存在这个问题



2025-03-02T13:39:33+08:00 - gpustack.worker.backends.llama_box - INFO - Starting llama-box server
0.00.001.566 I 
0.00.001.581 I arguments  : C:\Users\youkai\pipx\venvs\gpustack\Lib\site-packages\gpustack\third_party\bin\llama-box\llama-box.exe --host 0.0.0.0 --embeddings --gpu-layers 29 --parallel 4 --ctx-size 8192 --port 40228 --model D:\DeepSeek-R1\DeepSeek-R1-1.5b.gguf --alias DeepSeek-R1-1.5b --no-mmap --no-warmup
0.00.001.582 I version    : v0.0.117 (315b735)
0.00.001.582 I compiler   : unknown
0.00.001.582 I target     : unknown
0.00.001.582 I vendor     : llama.cpp 27d135c9 (4598), stable-diffusion.cpp 102953d (203)
0.00.015.808 I ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
0.00.015.813 I ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
0.00.015.814 I ggml_cuda_init: found 1 CUDA devices:
0.00.015.821 I   Device 0: Tesla M40 24GB, compute capability 5.2, VMM: yes
0.00.016.875 I system_info: n_threads = 12 (n_threads_batch = 12) / 20 | CUDA : ARCHS = 600,610,700,750,800,860,890,900 | F16 = 1 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | 
0.00.016.878 I 
0.00.017.362 I srv                      main: listening, hostname = 0.0.0.0, port = 40228, n_threads = 6 + 2
0.00.028.693 I srv                      main: loading model
0.00.028.703 I srv                load_model: loading model 'D:\DeepSeek-R1\DeepSeek-R1-1.5b.gguf'
0.00.068.376 I llama_model_load_from_file_impl: using device CUDA0 (Tesla M40 24GB) - 22115 MiB free
0.00.196.753 I llama_model_loader: loaded meta data with 26 key-value pairs and 339 tensors from D:\DeepSeek-R1\DeepSeek-R1-1.5b.gguf (version GGUF V3 (latest))
0.00.196.788 I llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
0.00.196.794 I llama_model_loader: - kv   0:                       general.architecture str              = qwen2
0.00.196.795 I llama_model_loader: - kv   1:                               general.type str              = model
0.00.196.796 I llama_model_loader: - kv   2:                               general.name str              = DeepSeek R1 Distill Qwen 1.5B
0.00.196.797 I llama_model_loader: - kv   3:                           general.basename str              = DeepSeek-R1-Distill-Qwen
0.00.196.797 I llama_model_loader: - kv   4:                         general.size_label str              = 1.5B
0.00.196.803 I llama_model_loader: - kv   5:                          qwen2.block_count u32              = 28
0.00.196.803 I llama_model_loader: - kv   6:                       qwen2.context_length u32              = 131072
0.00.196.804 I llama_model_loader: - kv   7:                     qwen2.embedding_length u32              = 1536
0.00.196.804 I llama_model_loader: - kv   8:                  qwen2.feed_forward_length u32              = 8960
0.00.196.804 I llama_model_loader: - kv   9:                 qwen2.attention.head_count u32              = 12
0.00.196.805 I llama_model_loader: - kv  10:              qwen2.attention.head_count_kv u32              = 2
0.00.196.831 I llama_model_loader: - kv  11:                       qwen2.rope.freq_base f32              = 10000.000000
0.00.196.836 I llama_model_loader: - kv  12:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
0.00.196.837 I llama_model_loader: - kv  13:                          general.file_type u32              = 15
0.00.196.837 I llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = gpt2
0.00.196.838 I llama_model_loader: - kv  15:                         tokenizer.ggml.pre str              = qwen2
0.00.221.648 I llama_model_loader: - kv  16:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
0.00.232.331 I llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
0.00.257.091 I llama_model_loader: - kv  18:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
0.00.257.100 I llama_model_loader: - kv  19:                tokenizer.ggml.bos_token_id u32              = 151646
0.00.257.100 I llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151643
0.00.257.101 I llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
0.00.257.102 I llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
0.00.257.102 I llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
0.00.257.106 I llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {% if not add_generation_prompt is de...
0.00.257.106 I llama_model_loader: - kv  25:               general.quantization_version u32              = 2
0.00.257.107 I llama_model_loader: - type  f32:  141 tensors
0.00.257.107 I llama_model_loader: - type q4_K:  169 tensors
0.00.257.108 I llama_model_loader: - type q6_K:   29 tensors
0.00.257.109 I print_info: file format = GGUF V3 (latest)
0.00.257.115 I print_info: file type   = Q4_K - Medium
0.00.257.118 I print_info: file size   = 1.04 GiB (5.00 BPW) 
0.00.300.442 I srv       log_server_response: rid  | GET /v1/models 127.0.0.1:50075 | status 503 | cost 0.27s
0.00.349.317 W load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
0.00.349.583 I load: special tokens cache size = 22
0.00.368.803 I load: token to piece cache size = 0.9310 MB
0.00.368.814 I print_info: arch             = qwen2
0.00.368.815 I print_info: vocab_only       = 0
0.00.368.815 I print_info: n_ctx_train      = 131072
0.00.368.815 I print_info: n_embd           = 1536
0.00.368.816 I print_info: n_layer          = 28
0.00.368.832 I print_info: n_head           = 12
0.00.368.834 I print_info: n_head_kv        = 2
0.00.368.835 I print_info: n_rot            = 128
0.00.368.835 I print_info: n_swa            = 0
0.00.368.835 I print_info: n_embd_head_k    = 128
0.00.368.835 I print_info: n_embd_head_v    = 128
0.00.368.837 I print_info: n_gqa            = 6
0.00.368.838 I print_info: n_embd_k_gqa     = 256
0.00.368.839 I print_info: n_embd_v_gqa     = 256
0.00.368.840 I print_info: f_norm_eps       = 0.0e+00
0.00.368.841 I print_info: f_norm_rms_eps   = 1.0e-06
0.00.368.841 I print_info: f_clamp_kqv      = 0.0e+00
0.00.368.842 I print_info: f_max_alibi_bias = 0.0e+00
0.00.368.842 I print_info: f_logit_scale    = 0.0e+00
0.00.368.843 I print_info: n_ff             = 8960
0.00.368.843 I print_info: n_expert         = 0
0.00.368.844 I print_info: n_expert_used    = 0
0.00.368.844 I print_info: causal attn      = 1
0.00.368.844 I print_info: pooling type     = 0
0.00.368.844 I print_info: rope type        = 2
0.00.368.845 I print_info: rope scaling     = linear
0.00.368.845 I print_info: freq_base_train  = 10000.0
0.00.368.846 I print_info: freq_scale_train = 1
0.00.368.846 I print_info: n_ctx_orig_yarn  = 131072
0.00.368.847 I print_info: rope_finetuned   = unknown
0.00.368.847 I print_info: ssm_d_conv       = 0
0.00.368.847 I print_info: ssm_d_inner      = 0
0.00.368.847 I print_info: ssm_d_state      = 0
0.00.368.847 I print_info: ssm_dt_rank      = 0
0.00.368.847 I print_info: ssm_dt_b_c_rms   = 0
0.00.368.848 I print_info: model type       = 1.5B
0.00.368.849 I print_info: model params     = 1.78 B
0.00.368.849 I print_info: general.name     = DeepSeek R1 Distill Qwen 1.5B
0.00.368.851 I print_info: vocab type       = BPE
0.00.368.851 I print_info: n_vocab          = 151936
0.00.368.852 I print_info: n_merges         = 151387
0.00.368.852 I print_info: BOS token        = 151646 '<｜begin▁of▁sentence｜>'
0.00.368.852 I print_info: EOS token        = 151643 '<｜end▁of▁sentence｜>'
0.00.368.852 I print_info: EOT token        = 151643 '<｜end▁of▁sentence｜>'
0.00.368.853 I print_info: PAD token        = 151643 '<｜end▁of▁sentence｜>'
0.00.368.853 I print_info: LF token         = 198 'Ċ'
0.00.368.854 I print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
0.00.368.854 I print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
0.00.368.854 I print_info: FIM MID token    = 151660 '<|fim_middle|>'
0.00.368.855 I print_info: FIM PAD token    = 151662 '<|fim_pad|>'
0.00.368.855 I print_info: FIM REP token    = 151663 '<|repo_name|>'
0.00.368.856 I print_info: FIM SEP token    = 151664 '<|file_sep|>'
0.00.368.856 I print_info: EOG token        = 151643 '<｜end▁of▁sentence｜>'
0.00.368.856 I print_info: EOG token        = 151662 '<|fim_pad|>'
0.00.368.857 I print_info: EOG token        = 151663 '<|repo_name|>'
0.00.368.857 I print_info: EOG token        = 151664 '<|file_sep|>'
0.00.368.857 I print_info: max token length = 256
0.00.373.087 I load_tensors: offloading 28 repeating layers to GPU
0.00.373.091 I load_tensors: offloading output layer to GPU
0.00.373.091 I load_tensors: offloaded 29/29 layers to GPU
0.00.373.093 I load_tensors:          CPU model buffer size =   125.19 MiB
0.00.373.094 I load_tensors:        CUDA0 model buffer size =   934.70 MiB
0.01.800.899 I llama_init_from_model: n_seq_max     = 4
0.01.800.904 I llama_init_from_model: n_ctx         = 8192
0.01.800.904 I llama_init_from_model: n_ctx_per_seq = 2048
0.01.800.904 I llama_init_from_model: n_batch       = 2048
0.01.800.905 I llama_init_from_model: n_ubatch      = 512
0.01.800.905 I llama_init_from_model: flash_attn    = 0
0.01.800.907 I llama_init_from_model: freq_base     = 10000.0
0.01.800.909 I llama_init_from_model: freq_scale    = 1
0.01.800.910 W llama_init_from_model: n_ctx_per_seq (2048) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
0.01.800.918 I llama_kv_cache_init: kv_size = 8192, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 28, can_shift = 1
0.01.820.131 I llama_kv_cache_init:      CUDA0 KV buffer size =   224.00 MiB
0.01.820.139 I llama_init_from_model: KV self size  =  224.00 MiB, K (f16):  112.00 MiB, V (f16):  112.00 MiB
0.01.820.403 I llama_init_from_model:  CUDA_Host  output buffer size =     0.02 MiB
0.01.825.494 I llama_init_from_model:      CUDA0 compute buffer size =   299.75 MiB
0.01.825.499 I llama_init_from_model:  CUDA_Host compute buffer size =    19.01 MiB
0.01.825.500 I llama_init_from_model: graph nodes  = 986
0.01.825.500 I llama_init_from_model: graph splits = 2
0.01.825.506 I common_init_from_params: setting dry_penalty_last_n to ctx_size = 8192
0.01.825.511 I srv                load_model: prompt caching enabled
0.01.830.855 I srv                load_model: chat template, built_in: true, alias: deepseek3, tool call: unsupported, example:
You are a helpful assistant
<｜User｜>Hello<｜Assistant｜>Hi there<｜end▁of▁sentence｜><｜User｜>How are you?<｜Assistant｜>
0.01.830.860 I srv                      main: initializing server
0.01.830.861 I srv                      init: initializing slots, n_slots = 4
0.01.830.954 I srv                      main: starting server
0.03.319.697 I srv        log_server_request: rid 3290972 | GET /v1/models 127.0.0.1:50078
0.03.319.794 I srv       log_server_response: rid 3290972 | GET /v1/models 127.0.0.1:50078 | status 200 | cost 0.00s
0.03.675.185 I srv        log_server_request: rid 3646455 | GET /v1/models 192.168.0.172:50080
0.03.675.424 I srv       log_server_response: rid 3646455 | GET /v1/models 192.168.0.172:50080 | status 200 | cost 0.00s
0.14.190.793 I srv        log_server_request: rid 14162062 | POST /v1/chat/completions 192.168.0.172:50093
0.14.191.493 I srv oaicompat_completions_req: rid 14162062 | {"messages":"[...]","seed":null,"stop":null,"temperature":1,"top_p":1,"max_tokens":1024,"model":"DeepSeek-R1-1.5b","stream":true,"stream_options":{"include_usage":true}}
D:\a\llama-box\llama-box\llama.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:72: 0.14.197.330 CUDA errorE 
ggml_cuda_compute_forward: RMS_NORM failed
0.14.197.339 E CUDA error: no kernel image is available for execution on the device
0.14.197.342 E   current device: 0, in function ggml_cuda_compute_forward at D:\a\llama-box\llama-box\llama.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:2313

![Image](https://github.com/user-attachments/assets/5445a777-a5b5-49db-af95-aba429b14562)

![Image](https://github.com/user-attachments/assets/db9442b1-271a-414a-b0ff-d56d49ba9d94)

os:windows11
cpu:12700k
mem:128G

**Comment by pengjiang80** [comment]
Please run the following command and try again.

gpustack download-tools --device cuda

**Comment by thxCode** [comment]
It looks like 5090D uses 10.0 Compute Capability, which is currently incompatible with the llama box.

<img width="698" alt="Image" src="https://github.com/user-attachments/assets/b6b525dc-1d45-4fb1-b4dc-4cd21a5c63b6" />

**Comment by youkai1981** [comment]
在显卡更换为m40的情况下依然存在问题

**Comment by youkai1981** [comment]
换成m40了，并且执行了gpustack download-tools

![Image](https://github.com/user-attachments/assets/acd2915a-322b-4cab-81fb-5ea884a0d426)

![Image](https://github.com/user-attachments/assets/38cc332a-ade8-46c5-8500-5501582560a0)

![Image](https://github.com/user-attachments/assets/3f5bba3f-861f-4965-85f4-02c1eeb79f99)

[log.txt](https://github.com/user-attachments/files/19053051/log.txt)

**Comment by thxCode** [comment]
> 换成m40了，并且执行了gpustack download-tools
> 
> ![Image](https://github.com/user-attachments/assets/acd2915a-322b-4cab-81fb-5ea884a0d426)
> 
> ![Image](https://github.com/user-attachments/assets/38cc332a-ade8-46c5-8500-5501582560a0)
> 
> ![Image](https://github.com/user-attachments/assets/3f5bba3f-861f-4965-85f4-02c1eeb79f99)
> 
> [log.txt](https://github.com/user-attachments/files/19053051/log.txt)

llama-box declares compute capabilities supported on its site, please take a look.https://github.com/gpustack/llama-box?tab=readme-ov-file#supports

<img width="997" alt="Image" src="https://github.com/user-attachments/assets/34d903ee-8943-4423-97ff-95c37d5104b4" />

**Comment by thxCode** [comment]
llama-box CUDA 12.8 built released in https://github.com/gpustack/llama-box/releases/tag/v0.0.124.

**Comment by youkai1981** [comment]
thank you

**Comment by Finenyaco** [comment]
GPUStack version: main 
llama-box version: v0.0.129

The issue still persists.

```
2025-04-11T09:29:00+00:00 - gpustack.worker.backends.base - INFO - Preparing model files...
2025-04-11T09:29:02+00:00 - gpustack.worker.backends.base - INFO - Model files are ready.
2025-04-11T09:29:02+00:00 - gpustack.utils.profiling - DEBUG - __init__ execution time: 2.139927387237549 seconds
2025-04-11T09:29:02+00:00 - gpustack.worker.backends.llama_box - INFO - Starting llama-box server
2025-04-11T09:29:02+00:00 - gpustack.worker.backends.llama_box - DEBUG - Run llama-box: /usr/local/lib/python3.11/dist-packages/gpustack/third_party/bin/llama-box/llama-box with arguments: --host 0.0.0.0 --embeddings --gpu-layers 25 --parallel 4 --ctx-size 8192 --port 40061 --model /root/data/cache/huggingface/Qwen/Qwen2.5-0.5B-Instruct-GGUF/qwen2.5-0.5b-instruct-q4_k_m.gguf --alias qwen2.5 --no-mmap --no-warmup
0.00.001.071 I 
0.00.001.078 I arguments  : /usr/local/lib/python3.11/dist-packages/gpustack/third_party/bin/llama-box/llama-box --host 0.0.0.0 --embeddings --gpu-layers 25 --parallel 4 --ctx-size 8192 --port 40061 --model /root/data/cache/huggingface/Qwen/Qwen2.5-0.5B-Instruct-GGUF/qwen2.5-0.5b-instruct-q4_k_m.gguf --alias qwen2.5 --no-mmap --no-warmup
0.00.001.079 I version    : v0.0.129 (ab96f41)
0.00.001.081 I compiler   : cc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
0.00.001.081 I target     : x86_64-redhat-linux
0.00.001.081 I vendor     : llama.cpp 97a20c01 (5034), stable-diffusion.cpp 3eb18db (204)
0.00.019.521 I ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
0.00.019.523 I ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
0.00.019.523 I ggml_cuda_init: found 1 CUDA devices:
0.00.021.929 I   Device 0: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes
0.00.024.976 I system_info: n_threads = 16 (n_threads_batch = 16) / 32 | CUDA : ARCHS = 600,610,700,750,800,860,890,900 | F16 = 1 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | FA_ALL_QUANTS = 1 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | 
0.00.024.978 I 
0.00.025.004 I main: binding port with default address family
0.00.025.031 I srv                      main: listening, hostname = 0.0.0.0, port = 40061, n_threads_http = 16 + 2
0.00.026.152 I srv                      main: loading model
0.00.026.154 I srv                load_model: loading model '/root/data/cache/huggingface/Qwen/Qwen2.5-0.5B-Instruct-GGUF/qwen2.5-0.5b-instruct-q4_k_m.gguf'
0.00.108.044 I llama_model_load_from_file_impl: using device CUDA0 (NVIDIA GeForce RTX 5090) - 31113 MiB free
0.00.135.156 I llama_model_loader: loaded meta data with 26 key-value pairs and 291 tensors from /root/data/cache/huggingface/Qwen/Qwen2.5-0.5B-Instruct-GGUF/qwen2.5-0.5b-instruct-q4_k_m.gguf (version GGUF V3 (latest))
0.00.135.163 I llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
0.00.135.166 I llama_model_loader: - kv   0:                       general.architecture str              = qwen2
0.00.135.167 I llama_model_loader: - kv   1:                               general.type str              = model
0.00.135.167 I llama_model_loader: - kv   2:                               general.name str              = qwen2.5-0.5b-instruct
0.00.135.167 I llama_model_loader: - kv   3:                            general.version str              = v0.1
0.00.135.168 I llama_model_loader: - kv   4:                           general.finetune str              = qwen2.5-0.5b-instruct
0.00.135.168 I llama_model_loader: - kv   5:                         general.size_label str              = 630M
0.00.135.172 I llama_model_loader: - kv   6:                          qwen2.block_count u32              = 24
0.00.135.172 I llama_model_loader: - kv   7:                       qwen2.context_length u32              = 32768
0.00.135.173 I llama_model_loader: - kv   8:                     qwen2.embedding_length u32              = 896
0.00.135.173 I llama_model_loader: - kv   9:                  qwen2.feed_forward_length u32              = 4864
0.00.135.173 I llama_model_loader: - kv  10:                 qwen2.attention.head_count u32              = 14
0.00.135.174 I llama_model_loader: - kv  11:              qwen2.attention.head_count_kv u32              = 2
0.00.135.177 I llama_model_loader: - kv  12:                       qwen2.rope.freq_base f32              = 1000000.000000
0.00.135.178 I llama_model_loader: - kv  13:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
0.00.135.179 I llama_model_loader: - kv  14:                          general.file_type u32              = 15
0.00.135.179 I llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
0.00.135.179 I llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = qwen2
0.00.156.594 I llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
0.00.163.791 I llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
0.00.185.546 I llama_model_loader: - kv  19:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
0.00.185.548 I llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151645
0.00.185.548 I llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
0.00.185.549 I llama_model_loader: - kv  22:                tokenizer.ggml.bos_token_id u32              = 151643
0.00.185.550 I llama_model_loader: - kv  23:               tokenizer.ggml.add_bos_token bool             = false
0.00.185.551 I llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
0.00.185.551 I llama_model_loader: - kv  25:               general.quantization_version u32              = 2
0.00.185.552 I llama_model_loader: - type  f32:  121 tensors
0.00.185.552 I llama_model_loader: - type q5_0:  133 tensors
0.00.185.552 I llama_model_loader: - type q8_0:   13 tensors
0.00.185.552 I llama_model_loader: - type q4_K:   12 tensors
0.00.185.552 I llama_model_loader: - type q6_K:   12 tensors
0.00.185.553 I print_info: file format = GGUF V3 (latest)
0.00.185.554 I print_info: file type   = Q4_K - Medium
0.00.185.555 I print_info: file size   = 462.96 MiB (6.16 BPW) 
0.00.238.083 I load: special tokens cache size = 22
0.00.322.648 I load: token to piece cache size = 0.9310 MB
0.00.322.660 I print_info: arch             = qwen2
0.00.322.660 I print_info: vocab_only       = 0
0.00.322.661 I print_info: n_ctx_train      = 32768
0.00.322.661 I print_info: n_embd           = 896
0.00.322.661 I print_info: n_layer          = 24
0.00.322.667 I print_info: n_head           = 14
0.00.322.668 I print_info: n_head_kv        = 2
0.00.322.669 I print_info: n_rot            = 64
0.00.322.669 I print_info: n_swa            = 0
0.00.322.669 I print_info: n_swa_pattern    = 1
0.00.322.669 I print_info: n_embd_head_k    = 64
0.00.322.669 I print_info: n_embd_head_v    = 64
0.00.322.670 I print_info: n_gqa            = 7
0.00.322.671 I print_info: n_embd_k_gqa     = 128
0.00.322.672 I print_info: n_embd_v_gqa     = 128
0.00.322.672 I print_info: f_norm_eps       = 0.0e+00
0.00.322.673 I print_info: f_norm_rms_eps   = 1.0e-06
0.00.322.673 I print_info: f_clamp_kqv      = 0.0e+00
0.00.322.673 I print_info: f_max_alibi_bias = 0.0e+00
0.00.322.674 I print_info: f_logit_scale    = 0.0e+00
0.00.322.674 I print_info: f_attn_scale     = 0.0e+00
0.00.322.675 I print_info: n_ff             = 4864
0.00.322.675 I print_info: n_expert         = 0
0.00.322.675 I print_info: n_expert_used    = 0
0.00.322.675 I print_info: causal attn      = 1
0.00.322.675 I print_info: pooling type     = 0
0.00.322.675 I print_info: rope type        = 2
0.00.322.676 I print_info: rope scaling     = linear
0.00.322.677 I print_info: freq_base_train  = 1000000.0
0.00.322.677 I print_info: freq_scale_train = 1
0.00.322.677 I print_info: n_ctx_orig_yarn  = 32768
0.00.322.677 I print_info: rope_finetuned   = unknown
0.00.322.677 I print_info: ssm_d_conv       = 0
0.00.322.678 I print_info: ssm_d_inner      = 0
0.00.322.678 I print_info: ssm_d_state      = 0
0.00.322.678 I print_info: ssm_dt_rank      = 0
0.00.322.678 I print_info: ssm_dt_b_c_rms   = 0
0.00.322.678 I print_info: model type       = 1B
0.00.322.679 I print_info: model params     = 630.17 M
0.00.322.679 I print_info: general.name     = qwen2.5-0.5b-instruct
0.00.322.680 I print_info: vocab type       = BPE
0.00.322.680 I print_info: n_vocab          = 151936
0.00.322.680 I print_info: n_merges         = 151387
0.00.322.680 I print_info: BOS token        = 151643 '<|endoftext|>'
0.00.322.680 I print_info: EOS token        = 151645 '<|im_end|>'
0.00.322.681 I print_info: EOT token        = 151645 '<|im_end|>'
0.00.322.681 I print_info: PAD token        = 151643 '<|endoftext|>'
0.00.322.681 I print_info: LF token         = 198 'Ċ'
0.00.322.681 I print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
0.00.322.681 I print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
0.00.322.681 I print_info: FIM MID token    = 151660 '<|fim_middle|>'
0.00.322.682 I print_info: FIM PAD token    = 151662 '<|fim_pad|>'
0.00.322.682 I print_info: FIM REP token    = 151663 '<|repo_name|>'
0.00.322.682 I print_info: FIM SEP token    = 151664 '<|file_sep|>'
0.00.322.682 I print_info: EOG token        = 151643 '<|endoftext|>'
0.00.322.682 I print_info: EOG token        = 151645 '<|im_end|>'
0.00.322.683 I print_info: EOG token        = 151662 '<|fim_pad|>'
0.00.322.683 I print_info: EOG token        = 151663 '<|repo_name|>'
0.00.322.683 I print_info: EOG token        = 151664 '<|file_sep|>'
0.00.322.683 I print_info: max token length = 256
0.00.322.684 I load_tensors: loading model tensors, this can take a while... (mmap = false)
0.00.354.703 I load_tensors: offloading 24 repeating layers to GPU
0.00.354.705 I load_tensors: offloading output layer to GPU
0.00.354.706 I load_tensors: offloaded 25/25 layers to GPU
0.00.354.710 I load_tensors:    CUDA_Host model buffer size =    89.26 MiB
0.00.354.710 I load_tensors:        CUDA0 model buffer size =   373.73 MiB
0.00.364.954 I loaded  19% model tensors into buffer
0.00.374.019 I loaded  49% model tensors into buffer
0.00.374.526 I loaded  50% model tensors into buffer
0.00.374.694 I loaded  51% model tensors into buffer
0.00.374.984 I loaded  52% model tensors into buffer
0.00.375.374 I loaded  53% model tensors into buffer
0.00.375.669 I loaded  54% model tensors into buffer
0.00.376.035 I loaded  55% model tensors into buffer
0.00.376.354 I loaded  56% model tensors into buffer
0.00.376.580 I loaded  57% model tensors into buffer
0.00.376.869 I loaded  58% model tensors into buffer
0.00.377.212 I loaded  59% model tensors into buffer
0.00.377.487 I loaded  60% model tensors into buffer
0.00.377.827 I loaded  61% model tensors into buffer
0.00.378.103 I loaded  62% model tensors into buffer
0.00.378.504 I loaded  63% model tensors into buffer
0.00.378.695 I loaded  64% model tensors into buffer
0.00.379.211 I loaded  65% model tensors into buffer
0.00.379.397 I loaded  66% model tensors into buffer
0.00.379.687 I loaded  67% model tensors into buffer
0.00.380.078 I loaded  68% model tensors into buffer
0.00.380.381 I loaded  69% model tensors into buffer
0.00.380.603 I loaded  70% model tensors into buffer
0.00.380.936 I loaded  71% model tensors into buffer
0.00.381.387 I loaded  72% model tensors into buffer
0.00.381.577 I loaded  73% model tensors into buffer
0.00.382.006 I loaded  74% model tensors into buffer
0.00.382.194 I loaded  75% model tensors into buffer
0.00.382.638 I loaded  76% model tensors into buffer
0.00.382.818 I loaded  77% model tensors into buffer
0.00.383.329 I loaded  78% model tensors into buffer
0.00.383.512 I loaded  79% model tensors into buffer
0.00.383.810 I loaded  80% model tensors into buffer
0.00.384.142 I loaded  81% model tensors into buffer
0.00.384.429 I loaded  82% model tensors into buffer
0.00.384.752 I loaded  83% model tensors into buffer
0.00.385.061 I loaded  84% model tensors into buffer
0.00.385.463 I loaded  85% model tensors into buffer
0.00.385.743 I loaded  86% model tensors into buffer
0.00.386.080 I loaded  87% model tensors into buffer
0.00.386.373 I loaded  88% model tensors into buffer
0.00.386.687 I loaded  89% model tensors into buffer
0.00.386.991 I loaded  90% model tensors into buffer
0.00.387.218 I loaded  91% model tensors into buffer
0.00.387.491 I loaded  92% model tensors into buffer
0.00.387.827 I loaded  93% model tensors into buffer
0.00.388.103 I loaded  94% model tensors into buffer
0.00.388.533 I loaded  95% model tensors into buffer
0.00.388.750 I loaded  96% model tensors into buffer
0.00.389.158 I loaded  97% model tensors into buffer
0.00.389.385 I loaded  98% model tensors into buffer
0.00.389.781 I loaded  99% model tensors into buffer
0.00.390.743 I loaded 100% model tensors into buffer
0.00.394.206 I llama_context: constructing llama_context
0.00.394.210 I llama_context: n_seq_max     = 4
0.00.394.210 I llama_context: n_ctx         = 8192
0.00.394.211 I llama_context: n_ctx_per_seq = 2048
0.00.394.211 I llama_context: n_batch       = 2048
0.00.394.211 I llama_context: n_ubatch      = 512
0.00.394.211 I llama_context: causal_attn   = 1
0.00.394.212 I llama_context: flash_attn    = 0
0.00.394.216 I llama_context: freq_base     = 1000000.0
0.00.394.216 I llama_context: freq_scale    = 1
0.00.394.217 W llama_context: n_ctx_per_seq (2048) < n_ctx_train (32768) -- the full capacity of the model will not be utilized
0.00.395.110 I llama_context:  CUDA_Host  output buffer size =     0.01 MiB
0.00.395.114 I init: kv_size = 8192, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 24, can_shift = 1
0.00.395.298 I init:      CUDA0 KV buffer size =    96.00 MiB
0.00.395.301 I llama_context: KV self size  =   96.00 MiB, K (f16):   48.00 MiB, V (f16):   48.00 MiB
0.00.410.597 I llama_context:      CUDA0 compute buffer size =   298.50 MiB
0.00.410.599 I llama_context:  CUDA_Host compute buffer size =    17.76 MiB
0.00.410.600 I llama_context: graph nodes  = 894
0.00.410.600 I llama_context: graph splits = 2
0.00.410.602 I common_init_from_params: setting dry_penalty_last_n to ctx_size = 8192
0.00.410.605 I srv                load_model: prompt caching enabled
0.00.420.369 I srv                load_model: chat template, built-in: true, jinja rendering: disabled, tool call: supported, reasoning: unsupported, example:
<|im_start|>system
You are a helpful assistant.
# Tools
You CAN call functions to assist with the user query. Do not make assumptions about what values to plug into functions.
You are provided with following function signatures within <tools></tools> XML tags:
<tools>
{"type": "function", "function": {"name": "get_weather", "description": "", "parameters": {"type":"object","properties":{"location":{"type":"string"}}}}}
{"type": "function", "function": {"name": "get_temperature", "description": "Return the temperature according to the location.", "parameters": {"type":"object","properties":{"location":{"type":"string"}}}}}
</tools>
When you can reply with your internal knowledge, reply directly without any function calls. Otherwise, try to do function calls without any explanations. For each function call, just generate an answer, no explanation before or after your answer, MUST return an JSON object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <arguments-json-object>}
</tool_call><|im_end|>
<|im_start|>user
Hello.<|im_end|>
<|im_start|>assistant
Hi! How can I help you today?<|im_end|>
<|im_start|>user
What is the weather like in Beijing?<|im_end|>
<|im_start|>assistant
<tool_call>
{"name":"get_weather","arguments":{"location":"Beijing"}}
</tool_call><|im_end|>
<|im_start|>user
{"weather":"Sunny"}<|im_end|>
<|im_start|>assistant
The weather is Sunny.<|im_end|>
<|im_start|>assistant
0.00.420.376 I srv                      main: initializing server
0.00.420.377 I srv                      init: initializing slots, n_slots = 4
0.00.420.429 I srv                      main: starting server
0.02.594.282 I srv        log_server_request: rid 237773363520 | GET /v1/models 172.19.0.2:51198
0.02.594.375 I srv       log_server_response: rid 237773363520 | GET /v1/models 172.19.0.2:51198 | status 200 | cost 0.00s
4.00.225.338 I srv        log_server_request: rid 238010994575 | POST /v1/chat/completions 127.0.0.1:50546
4.00.225.430 I srv oaicompat_completions_req: rid 238010994575 | {"messages":"[...]","seed":null,"stop":null,"temperature":0.8,"top_p":0.95,"max_tokens":1024,"frequency_penalty":0,"presence_penalty":0,"model":"qwen2.5","stream":true,"stream_options":{"include_usage":true}}
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:75: CUDA error
4.00.239.811 E ggml_cuda_compute_forward: RMS_NORM failed
4.00.239.815 E CUDA error: no kernel image is available for execution on the device
4.00.239.816 E   current device: 0, in function ggml_cuda_compute_forward at /home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2338
```

**Comment by Finenyaco** [comment]
The issue is resolved after updating to main (commit da3d558)
llama-box-linux-amd64-cuda-12.8 'v0.0.129'
