### ISSUE TITLE
Failed deploy model in Ascend 310P

### ISSUE THREAD

**Issue by linjiangyu2** [gpustack/gpustack#1514]
**Describe the bug**

**Steps to reproduce**

在Ascend 310P 的Atlas 300I DUO推理卡上通过Docker使用gpustack部署模型报错
已经重新替换了310p的llama-box和310p的算子包并且重启容器

报错日志：
```
When you can reply with your internal knowledge, reply directly without any function calls. Otherwise, try to do function calls without any explanations. For each function call, just generate an answer, no explanation before or after your answer, MUST return an JSON object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <arguments-json-object>}
</tool_call><|im_end|>
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
Hi there<|im_end|>
<|im_start|>user
How are you?<|im_end|>
<|im_start|>assistant
0.01.221.895 I srv                      main: initializing server
0.01.221.908 I srv                      init: initializing slots, n_slots = 4
0.01.222.084 I srv                      main: starting server
0.01.259.142 I srv        log_server_request: rid 6408352090 | GET /v1/models 127.0.0.1:37054
0.01.259.248 I srv       log_server_response: rid 6408352090 | GET /v1/models 127.0.0.1:37054 | status 200 | cost 0.00s
0.01.377.735 I srv        log_server_request: rid 6408470682 | GET /v1/models 172.17.0.2:48520
0.01.377.827 I srv       log_server_response: rid 6408470682 | GET /v1/models 172.17.0.2:48520 | status 200 | cost 0.00s
0.15.578.522 I srv        log_server_request: rid 6422671467 | POST /v1/chat/completions 172.17.0.2:48524
0.15.578.700 I srv oaicompat_completions_req: rid 6422671467 | {"messages":"[...]","model":"qwen2.5-0.5b-instruct","max_tokens":2048,"stream":true,"stream_options":{"include_usage":true}}
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp:63: CANN error0.15.643.149 E CANN error: EH9999: Inner Error!
EH9999: 2025-03-21-07:57:33.105.170  [Init][PlatformInfo]init runtime platform info failed, SocVersion = Ascend310P3[FUNC:ReportInnerError][FILE:log_inner.cpp][LINE:145]
        TraceBack (most recent call last):
        Fail to get core num from GE, core num get is 0.[FUNC:ParseAutoTilingRun][FILE:auto_tiling_rt2.cc][LINE:194]
        Op tiling compile info parse failed
        InitTilingParseCtx failed
        Kernel Run failed. opType: 3, Add
        launch failed for Add, errno:361001.
0.15.643.156 E   current device: 0, in function aclnn_values at /home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cann/aclnn_ops.cpp:1146
0.15.643.156 E   aclnnInplaceAdds(workspaceAddr, workspaceSize, executor, ctx.stream())
```

**Environment**

- GPUStack version:  gpustack/gpustack:v0.5.1-npu镜像
- OS: 银河麒麟V10 SP1
- GPU: Ascend 310P * 4

**Additional context**

**Comment by thxCode** [comment]
@linjiangyu2 can you view the running ascend plog to find some`[ERROR]` logs? here is a related issue with some debug information I can see, https://gitee.com/ascend/pytorch/issues/I9FM64?skip_mobile=true. cc @yungongzi tl;dr, start the container with `--privilage`. you guys can have a try.

**Comment by yungongzi** [comment]
一样的错误。增加--privilage参数启动。
```bash
2025-04-02T00:52:03+00:00 - gpustack.worker.downloaders - INFO - Retriving file lock
Downloading Model to directory: /var/lib/gpustack/cache/model_scope/Qwen/Qwen2.5-0.5B-Instruct-GGUF
2025-04-02T00:52:04+00:00 - gpustack.worker.backends.llama_box - INFO - Starting llama-box server
0.00.002.808 I 
0.00.002.857 I arguments  : /usr/local/python3.10/lib/python3.10/site-packages/gpustack/third_party/bin/llama-box/llama-box --host 0.0.0.0 --embeddings --gpu-layers 25 --parallel 4 --ctx-size 8192 --port 40008 --model /var/lib/gpustack/cache/model_scope/Qwen/Qwen2___5-0___5B-Instruct-GGUF/qwen2.5-0.5b-instruct-fp16.gguf --alias qwen2.5-0.5b-instruct --no-mmap --no-warmup
0.00.002.858 I version    : v0.0.117 (315b735)
0.00.002.858 I compiler   : cc (Ubuntu 11.4.0-2ubuntu1~20.04) 11.4.0
0.00.002.859 I target     : aarch64-linux-gnu
0.00.002.860 I vendor     : llama.cpp 27d135c9 (4598), stable-diffusion.cpp 102953d (203)
0.00.747.650 I system_info: n_threads = 96 (n_threads_batch = 96) / 96 | CPU : NEON = 1 | ARM_FMA = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | 
0.00.747.656 I 
0.00.747.803 I srv                      main: listening, hostname = 0.0.0.0, port = 40008, n_threads = 6 + 2
0.00.748.919 I srv                      main: loading model
0.00.748.923 I srv                load_model: loading model '/var/lib/gpustack/cache/model_scope/Qwen/Qwen2___5-0___5B-Instruct-GGUF/qwen2.5-0.5b-instruct-fp16.gguf'
0.00.749.087 I llama_model_load_from_file_impl: using device CANN0 (Ascend310P3) - 43366 MiB free
0.00.802.054 I llama_model_loader: loaded meta data with 26 key-value pairs and 291 tensors from /var/lib/gpustack/cache/model_scope/Qwen/Qwen2___5-0___5B-Instruct-GGUF/qwen2.5-0.5b-instruct-fp16.gguf (version GGUF V3 (latest))
0.00.802.075 I llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
0.00.802.081 I llama_model_loader: - kv   0:                       general.architecture str              = qwen2
0.00.802.082 I llama_model_loader: - kv   1:                               general.type str              = model
0.00.802.084 I llama_model_loader: - kv   2:                               general.name str              = qwen2.5-0.5b-instruct
0.00.802.085 I llama_model_loader: - kv   3:                            general.version str              = v0.1
0.00.802.086 I llama_model_loader: - kv   4:                           general.finetune str              = qwen2.5-0.5b-instruct
0.00.802.087 I llama_model_loader: - kv   5:                         general.size_label str              = 630M
0.00.802.091 I llama_model_loader: - kv   6:                          qwen2.block_count u32              = 24
0.00.802.092 I llama_model_loader: - kv   7:                       qwen2.context_length u32              = 8192
0.00.802.093 I llama_model_loader: - kv   8:                     qwen2.embedding_length u32              = 896
0.00.802.094 I llama_model_loader: - kv   9:                  qwen2.feed_forward_length u32              = 4864
0.00.802.095 I llama_model_loader: - kv  10:                 qwen2.attention.head_count u32              = 14
0.00.802.097 I llama_model_loader: - kv  11:              qwen2.attention.head_count_kv u32              = 2
0.00.802.108 I llama_model_loader: - kv  12:                       qwen2.rope.freq_base f32              = 1000000.000000
0.00.802.111 I llama_model_loader: - kv  13:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
0.00.802.112 I llama_model_loader: - kv  14:                          general.file_type u32              = 1
0.00.802.113 I llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
0.00.802.114 I llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = qwen2
0.00.831.918 I llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
0.00.854.922 I llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
0.00.884.178 I llama_model_loader: - kv  19:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
0.00.884.188 I llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151645
0.00.884.190 I llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
0.00.884.191 I llama_model_loader: - kv  22:                tokenizer.ggml.bos_token_id u32              = 151643
0.00.884.193 I llama_model_loader: - kv  23:               tokenizer.ggml.add_bos_token bool             = false
0.00.884.198 I llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
0.00.884.199 I llama_model_loader: - kv  25:               general.quantization_version u32              = 2
0.00.884.200 I llama_model_loader: - type  f32:  121 tensors
0.00.884.201 I llama_model_loader: - type  f16:  170 tensors
0.00.884.203 I print_info: file format = GGUF V3 (latest)
0.00.884.204 I print_info: file type   = F16
0.00.884.211 I print_info: file size   = 1.17 GiB (16.00 BPW) 
0.01.039.053 I load: special tokens cache size = 22
0.01.111.231 I load: token to piece cache size = 0.9310 MB
0.01.111.252 I print_info: arch             = qwen2
0.01.111.253 I print_info: vocab_only       = 0
0.01.111.254 I print_info: n_ctx_train      = 8192
0.01.111.254 I print_info: n_embd           = 896
0.01.111.255 I print_info: n_layer          = 24
0.01.111.269 I print_info: n_head           = 14
0.01.111.272 I print_info: n_head_kv        = 2
0.01.111.272 I print_info: n_rot            = 64
0.01.111.273 I print_info: n_swa            = 0
0.01.111.274 I print_info: n_embd_head_k    = 64
0.01.111.274 I print_info: n_embd_head_v    = 64
0.01.111.276 I print_info: n_gqa            = 7
0.01.111.277 I print_info: n_embd_k_gqa     = 128
0.01.111.279 I print_info: n_embd_v_gqa     = 128
0.01.111.280 I print_info: f_norm_eps       = 0.0e+00
0.01.111.283 I print_info: f_norm_rms_eps   = 1.0e-06
0.01.111.284 I print_info: f_clamp_kqv      = 0.0e+00
0.01.111.284 I print_info: f_max_alibi_bias = 0.0e+00
0.01.111.285 I print_info: f_logit_scale    = 0.0e+00
0.01.111.287 I print_info: n_ff             = 4864
0.01.111.287 I print_info: n_expert         = 0
0.01.111.288 I print_info: n_expert_used    = 0
0.01.111.288 I print_info: causal attn      = 1
0.01.111.289 I print_info: pooling type     = 0
0.01.111.289 I print_info: rope type        = 2
0.01.111.290 I print_info: rope scaling     = linear
0.01.111.293 I print_info: freq_base_train  = 1000000.0
0.01.111.293 I print_info: freq_scale_train = 1
0.01.111.294 I print_info: n_ctx_orig_yarn  = 8192
0.01.111.295 I print_info: rope_finetuned   = unknown
0.01.111.295 I print_info: ssm_d_conv       = 0
0.01.111.295 I print_info: ssm_d_inner      = 0
0.01.111.296 I print_info: ssm_d_state      = 0
0.01.111.296 I print_info: ssm_dt_rank      = 0
0.01.111.297 I print_info: ssm_dt_b_c_rms   = 0
0.01.111.297 I print_info: model type       = 1B
0.01.111.299 I print_info: model params     = 630.17 M
0.01.111.300 I print_info: general.name     = qwen2.5-0.5b-instruct
0.01.111.302 I print_info: vocab type       = BPE
0.01.111.302 I print_info: n_vocab          = 151936
0.01.111.303 I print_info: n_merges         = 151387
0.01.111.303 I print_info: BOS token        = 151643 '<|endoftext|>'
0.01.111.304 I print_info: EOS token        = 151645 '<|im_end|>'
0.01.111.304 I print_info: EOT token        = 151645 '<|im_end|>'
0.01.111.305 I print_info: PAD token        = 151643 '<|endoftext|>'
0.01.111.306 I print_info: LF token         = 198 'Ċ'
0.01.111.307 I print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
0.01.111.307 I print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
0.01.111.308 I print_info: FIM MID token    = 151660 '<|fim_middle|>'
0.01.111.308 I print_info: FIM PAD token    = 151662 '<|fim_pad|>'
0.01.111.309 I print_info: FIM REP token    = 151663 '<|repo_name|>'
0.01.111.309 I print_info: FIM SEP token    = 151664 '<|file_sep|>'
0.01.111.310 I print_info: EOG token        = 151643 '<|endoftext|>'
0.01.111.310 I print_info: EOG token        = 151645 '<|im_end|>'
0.01.111.311 I print_info: EOG token        = 151662 '<|fim_pad|>'
0.01.111.311 I print_info: EOG token        = 151663 '<|repo_name|>'
0.01.111.312 I print_info: EOG token        = 151664 '<|file_sep|>'
0.01.111.313 I print_info: max token length = 256
0.01.120.406 I load_tensors: offloading 24 repeating layers to GPU
0.01.120.410 I load_tensors: offloading output layer to GPU
0.01.120.411 I load_tensors: offloaded 25/25 layers to GPU
0.01.120.416 I load_tensors:    CANN_Host model buffer size =   259.66 MiB
0.01.120.417 I load_tensors:        CANN0 model buffer size =   942.43 MiB
0.01.468.378 I llama_init_from_model: n_seq_max     = 4
0.01.468.386 I llama_init_from_model: n_ctx         = 8192
0.01.468.386 I llama_init_from_model: n_ctx_per_seq = 2048
0.01.468.387 I llama_init_from_model: n_batch       = 2048
0.01.468.388 I llama_init_from_model: n_ubatch      = 512
0.01.468.389 I llama_init_from_model: flash_attn    = 0
0.01.468.400 I llama_init_from_model: freq_base     = 1000000.0
0.01.468.402 I llama_init_from_model: freq_scale    = 1
0.01.468.403 W llama_init_from_model: n_ctx_per_seq (2048) < n_ctx_train (8192) -- the full capacity of the model will not be utilized
0.01.468.491 I llama_kv_cache_init: kv_size = 8192, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 24, can_shift = 1
0.01.472.937 I llama_kv_cache_init:      CANN0 KV buffer size =    96.00 MiB
0.01.472.943 I llama_init_from_model: KV self size  =   96.00 MiB, K (f16):   48.00 MiB, V (f16):   48.00 MiB
0.01.473.037 I llama_init_from_model:  CANN_Host  output buffer size =     0.01 MiB
0.01.477.609 I llama_init_from_model:      CANN0 compute buffer size =   298.50 MiB
0.01.477.615 I llama_init_from_model:  CANN_Host compute buffer size =    17.76 MiB
0.01.477.617 I llama_init_from_model: graph nodes  = 846
0.01.477.621 I llama_init_from_model: graph splits = 2
0.01.477.625 I common_init_from_params: setting dry_penalty_last_n to ctx_size = 8192
0.01.477.633 I srv                load_model: prompt caching enabled
0.01.557.661 I srv                load_model: chat template, built_in: true, alias: chatml, tool call: supported, example:
<|im_start|>system
You are a helpful assistant
# Tools
You CAN call functions to assist with the user query. Do not make assumptions about what values to plug into functions.
You are provided with following function signatures within <tools></tools> XML tags:
<tools>
{"type": "function", "function": {"name": "get_weather", "description": "", "parameters": {"type":"object","properties":{"location":{"type":"string"}}}}}
{"type": "function", "function": {"name": "get_temperature", "description": "Return the temperature according to the location.", "parameters": {"type":"object","properties":{"location":{"type":"string"}}}}}
</tools>
When you can reply with your internal knowledge, reply directly without any function calls. Otherwise, try to do function calls without any explanations. For each function call, just generate an answer, no explanation before or after your answer, MUST return an JSON object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <arguments-json-object>}
</tool_call><|im_end|>
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
Hi there<|im_end|>
<|im_start|>user
How are you?<|im_end|>
<|im_start|>assistant
0.01.557.670 I srv                      main: initializing server
0.01.557.673 I srv                      init: initializing slots, n_slots = 4
0.01.557.839 I srv                      main: starting server
0.02.931.351 I srv        log_server_request: rid 489831308571 | GET /v1/models 127.0.0.1:35242
0.02.931.478 I srv       log_server_response: rid 489831308571 | GET /v1/models 127.0.0.1:35242 | status 200 | cost 0.00s
0.03.048.282 I srv        log_server_request: rid 489831425502 | GET /v1/models 172.17.0.2:53192
0.03.048.381 I srv       log_server_response: rid 489831425502 | GET /v1/models 172.17.0.2:53192 | status 200 | cost 0.00s
2.25.557.380 I srv        log_server_request: rid 489973934599 | POST /v1/chat/completions 172.17.0.2:56408
2.25.557.534 I srv oaicompat_completions_req: rid 489973934599 | {"messages":"[...]","seed":null,"stop":null,"temperature":1,"top_p":1,"max_tokens":1024,"model":"qwen2.5-0.5b-instruct","stream":true,"stream_options":{"include_usage":true}}
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp:63: CANN error2.25.616.469 E CANN error: EZ9999: Inner Error!
EZ9999: 2025-04-02-00:54:30.240.432  Parse dynamic kernel config fail.
        TraceBack (most recent call last):
        AclOpKernelInit failed opType
        Op Add does not has any binary.
        Kernel Run failed. opType: 3, Add
        launch failed for Add, errno:561000.
2.25.616.477 E   current device: 0, in function aclnn_values at /home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cann/aclnn_ops.cpp:1146
2.25.616.478 
E   aclnnInplaceAdds(workspaceAddr, workspaceSize, executor, ctx.stream())
```

**Comment by dmcslt** [comment]
@yungongzi install again，mount ascend-toolkit

**Comment by yungongzi** [comment]
> [@yungongzi](https://github.com/yungongzi) can you provide the host kernel information here via `uname -srm`?

Linux 4.19.90-25.45.v2101.ky10.aarch64 aarch64

**Comment by yungongzi** [comment]
> install again，mount ascend-toolkit

从新拉镜像安装吗？我是通过镜像安装的gpustack

**Comment by thxCode** [comment]
this should be a problem as we build a Docker image from Ubuntu 22.04 (kernel 6.0+), we can observe the same issue from our internal lab.

this issue is gone after we degraded the base image to Ubuntu 20.04 (kernel 4.0+).

we will build a new image in the next version, you can have a try later.

**Comment by Tendo33** [comment]
I used the latest `gpustack/gpustack:latest-npu` image, but the resource list did not show NPU resources after deployment.
This is my resource list:
```
(base) [root@localhost ~]# npu-smi info
+--------------------------------------------------------------------------------------------------------+
| npu-smi 24.1.rc3                                 Version: 24.1.rc3                                     |
+-------------------------------+-----------------+------------------------------------------------------+
| NPU     Name                  | Health          | Power(W)     Temp(C)           Hugepages-Usage(page) |
| Chip    Device                | Bus-Id          | AICore(%)    Memory-Usage(MB)                        |
+===============================+=================+======================================================+
| 1       310P3                 | OK              | NA           78                0     / 0             |
| 0       0                     | 0000:01:00.0    | 0            1240 / 44280                            |
+-------------------------------+-----------------+------------------------------------------------------+
| 1       310P3                 | OK              | NA           78                0     / 0             |
| 1       1                     | 0000:01:00.0    | 0            1680 / 43693                            |
+===============================+=================+======================================================+
| 2       310P3                 | OK              | NA           74                0     / 0             |
| 0       2                     | 0000:02:00.0    | 0            1341 / 44280                            |
+-------------------------------+-----------------+------------------------------------------------------+
| 2       310P3                 | OK              | NA           72                0     / 0             |
| 1       3                     | 0000:02:00.0    | 0            1575 / 43693                            |
+===============================+=================+======================================================+
| 4       310P3                 | OK              | NA           76                0     / 0             |
| 0       4                     | 0000:81:00.0    | 0            1295 / 44280                            |
+-------------------------------+-----------------+------------------------------------------------------+
| 4       310P3                 | OK              | NA           75                0     / 0             |
| 1       5                     | 0000:81:00.0    | 0            1624 / 43693                            |
+===============================+=================+======================================================+
| 5       310P3                 | OK              | NA           70                0     / 0             |
| 0       6                     | 0000:82:00.0    | 0            1646 / 44280                            |
+-------------------------------+-----------------+------------------------------------------------------+
| 5       310P3                 | OK              | NA           69                0     / 0             |
| 1       7                     | 0000:82:00.0    | 0            1320 / 43693                            |
+===============================+=================+======================================================+
+-------------------------------+-----------------+------------------------------------------------------+
| NPU     Chip                  | Process id      | Process name             | Process memory(MB)        |
+===============================+=================+======================================================+
| No running processes found in NPU 1                                                                    |
+===============================+=================+======================================================+
| No running processes found in NPU 2                                                                    |
+===============================+=================+======================================================+
| No running processes found in NPU 4                                                                    |
+===============================+=================+======================================================+
| No running processes found in NPU 5                                                                    |
+===============================+=================+======================================================+
```
What could be the possible reason?

**Comment by yungongzi** [comment]
> this should be a problem as we build a Docker image from Ubuntu 22.04 (kernel 6.0+), we can observe the same issue from our internal lab.
> 
> this issue is gone after we degraded the base image to Ubuntu 20.04 (kernel 4.0+).
> 
> we will build a new image in the next version, you can have a try later.

好的，期待下个版本！
