### ISSUE TITLE
run llama-box with RTX-5090D Failed-ggml_cuda_compute_forward: RMS_NORM failed

### ISSUE THREAD

**Issue by xtcn92** [gpustack/gpustack#2099]
**Describe the bug**
Run the LLM DeepSeek-R1-Distill-Llama-8B In GPUStack with the llama-box backend。
GPUStack version is v0.6.1 deployed by Docker（Docker version 26.1.3, build 26.1.3-0ubuntu1~24.04.1）。

Run GPUStack on the Ubuntu host. The GPUstack service starts normally,DeepSeek-R1-Distill-Llama-8B model are also running OK， but an exception occurred during the execution of a chat request, causing the chat to be unable to return information。The log information is as follows：

[2025-05-26 08:45:22.122529] I srv                      load: prompt caching enabled
[2025-05-26 08:45:22.122529] I srv                      load: context shifting partial supported
[2025-05-26 08:45:22.122544] I srv                      load: chat template, alias: deepseek3, built-in: true, jinja rendering: disabled, tool call: unsupported, reasoning: supported, example:
You are a helpful assistant.

<｜User｜>Hello.<｜Assistant｜>Hi! How can I help you today?<｜end▁of▁sentence｜><｜User｜>What is the weather like in Beijing?<｜Assistant｜>
[2025-05-26 08:45:22.122544] I srv                     start: starting
[2025-05-26 08:45:22.122545] I srv                     start: listening host = 0.0.0.0, port = 40061
[2025-05-26 08:45:22.122549] I srv                     start: server is ready
[2025-05-26 08:45:25.125688] I srv                   request: rid 9802758130 |  GET /v1/models 127.0.0.1:54418
[2025-05-26 08:45:25.125688] I srv                  response: rid 9802758130 |  GET /v1/models 127.0.0.1:54418 | status 200 | cost 0.18ms | opened
[2025-05-26 08:53:35.615976] I srv                   request: rid 10293046380 | POST /v1/chat/completions 127.0.0.1:49960
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:75: CUDA error
[2025-05-26 08:53:35.615991] E ggml_cuda_compute_forward: RMS_NORM failed
[2025-05-26 08:53:35.615991] E CUDA error: no kernel image is available for execution on the device
[2025-05-26 08:53:35.615991] E   current device: 0, in function ggml_cuda_compute_forward at /home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2359
[2025-05-26 08:53:35.615991] E   err

**Environment**

- GPUStack version: v0.6.1
- OS:  Docker host - Ubuntu 24.04.2 LTS (GNU/Linux 6.13.0-061300-generic x86_64)
- GPU:NVIDIA GeForce RTX 5090 D
- Cuda: nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Jan_15_19:20:09_PST_2025
Cuda compilation tools, release 12.8, V12.8.61
Build cuda_12.8.r12.8/compiler.35404655_0
- GPU driver:NVIDIA-SMI 570.153.02 Driver Version: 570.153.02 CUDA Version: 12.8

**Comment by xtcn92** [comment]
> [@xtcn92](https://github.com/xtcn92) Hi,
> 
> Are you using the `gpustack/gpustack:v0.6.1` image? For RTX 50 series GPUs, please use the `gpustack/gpustack:v0.6.1-cuda12.8` image instead.
> 
> If you're already using the gpustack/gpustack:v0.6.1-cuda12.8 image, please share the complete llama-box logs, thx
> 
> <img alt="Image" width="2000" src="https://private-user-images.githubusercontent.com/26084756/447538224-373ba1c0-2452-420f-a20c-7e3c75f8d194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDgzMTEzNDksIm5iZiI6MTc0ODMxMTA0OSwicGF0aCI6Ii8yNjA4NDc1Ni80NDc1MzgyMjQtMzczYmExYzAtMjQ1Mi00MjBmLWEyMGMtN2UzYzc1ZjhkMTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTI3VDAxNTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MzIyMjg0MTY1ZTJhYzE2NTQyNDJiNWFjYzlmNDEzODkxYWFjODQwZDQyMGE1MTY0NDhkZjIzOWUyNWQxZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bvV1IVW71hVbXx8FaVOIMNiDUUOziUiHRkxHz6l8FuA">

Yes, u're right. Gpustack/gpustack: v0.6.1-CUD12.8 is normal ,solved my problem. Tks!
