### ISSUE TITLE
PPU 运行失败

### ISSUE THREAD

**Issue by fq393** [gpustack/gpustack#5050]
### GPUStack version

2.1.1

### Operating System & CPU Architecture

Alibaba Cloud Linux release 3 (OpenAnolis Edition) 

### GPU

ppu

### ▶️ Steps to reproduce

运行命令
docker run -d --name gpustack-worker       -e "GPUSTACK_RUNTIME_DEPLOY_MIRRORED_NAME=gpustack-worker"       -e "GPUSTACK_TOKEN=xxxxxx"       -e "GPUSTACK_RUNTIME_DOCKER_RESOURCE_INJECTION_POLICY=CDI"       --restart=unless-stopped       --privileged       --network=host       --volume /var/run/docker.sock:/var/run/docker.sock       --volume gpustack-data:/var/lib/gpustack       --volume /usr/local/PPU_SDK:/usr/local/PPU_SDK:ro       --volume /var/run/cdi:/var/run/cdi       gpustack/gpustack       --server-url http://10.26.236.214       --worker-ip 10.20.32.218 

### ❌ Actual result

   create_workload(self._transform_workload_plan(workload_plan))
  File "/usr/local/lib/python3.11/dist-packages/gpustack_runtime/deployer/__init__.py", line 133, in create_workload
    dep.create(workload=workload)
  File "/usr/local/lib/python3.11/dist-packages/gpustack_runtime/deployer/__types__.py", line 1219, in wrapper
    return func(
           ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gpustack_runtime/deployer/__types__.py", line 1737, in create
    future.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gpustack_runtime/deployer/docker.py", line 379, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gpustack_runtime/deployer/docker.py", line 1541, in _create
    raise OperationError(msg) from e
gpustack_runtime.deployer.__types__.OperationError: Failed to create workload minimax-m2.5-LwBwv: Docker Server Error: could not select device driver "cdi" with capabilities: []

**Comment by thxCode** [comment]
@fq393 Check your Docker to see if it supports CDI or not.

**Comment by fq393** [comment]
## 问题已解决，记录完整排查过程供参考

**环境**：服务器 10.20.32.218，8张 PPU（阿里云平头哥），部署 MiniMax-M2.5 模型

---

### 问题一：CDI 设备驱动无法选择

原始报错：`could not select device driver "cdi" with capabilities: []`

**原因**：Docker 版本较旧，不原生支持 CDI。

**解法**：在 gpustack-worker 容器中设置环境变量，由 gpustack_runtime 自行实现 CDI 注入逻辑，绕过 Docker 原生 CDI：
```
GPUSTACK_RUNTIME_DOCKER_RESOURCE_INJECTION_POLICY=CDI
GPUSTACK_RUNTIME_DOCKER_CDI_SPECS_GENERATE=false   # 禁止 worker 覆盖手动维护的 CDI spec
GPUSTACK_RUNTIME_DEPLOY_CDI_SPECS_DIRECTORY=/var/run/cdi
```

---

### 问题二：CDI spec 缺少 ppu0 设备条目（HGML 索引偏移）

**现象**：容器创建失败，CDI spec 中找不到 UUID 为 `GPU-019ec20c-...` 的设备。

**根因**：HGML（`hgmlDeviceGetMinorNumber()`）返回的是基于 PCI 枚举顺序的硬件 minor 号（本机为 1~8），而不是 Linux 设备文件的顺序（0~7）。导致：
- ppu0 的 HGML minor = **8**（不是 0）
- gpustack_runtime 用 HGML minor 构造设备路径 `/dev/alixpu_ppu8`，但该文件不存在
- CDI spec 中也没有 index=8 的条目

**解法**：手动在 `/var/run/cdi/alibabacloud.com-ppu.yaml` 中补充 ppu0 的条目：
```yaml
- name: '8'      # HGML index
  containerEdits:
    deviceNodes:
    - path: /dev/alixpu_ppu0   # 实际设备文件（major: 237, minor: 1）
      major: 237
      minor: 1
      ...
- name: GPU-019ec20c-07a2-0a14-0000-0000407f7b2e   # UUID 条目同样指向 ppu0
  containerEdits:
    deviceNodes:
    - path: /dev/alixpu_ppu0
```

---

### 问题三：CUDA_VISIBLE_DEVICES 值错误导致 `invalid device ordinal`

**现象**：容器内报 `torch.AcceleratorError: CUDA error: invalid device ordinal`，`CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7,8`。

**根因**：gpustack 默认用 HGML minor 号（本机为 1~8）设置 `CUDA_VISIBLE_DEVICES`，但容器内 HGML 使用 0-based 枚举（0~7），导致索引 8 越界。

**解法**：在 gpustack-worker 容器中添加：
```
GPUSTACK_RUNTIME_DEPLOY_BACKEND_VISIBLE_DEVICES_VALUE_ALIGNMENT=ASCEND_RT_VISIBLE_DEVICES,NPU_VISIBLE_DEVICES,CUDA_VISIBLE_DEVICES
```
这样 gpustack 会使用顺序 0-based 索引（`0,1,2,3,4,5,6,7`）而非 HGML minor 号。

---

### 问题四：NCCL 找不到网络接口

**现象**：`NCCL ERROR Bootstrap: no socket interface found`

**根因**：推理镜像内硬编码了 `NCCL_SOCKET_IFNAME=eth0`，但宿主机网卡为 `ens1f0np0`，且 gpustack server 下发的 workload 配置中也包含 `eth0`，mirrored deployment 无法覆盖。

**解法**：在 CDI spec 全局 `containerEdits.env` 中注入，CDI env 优先级高于容器配置：
```yaml
# /var/run/cdi/alibabacloud.com-ppu.yaml
containerEdits:
  env:
  - NVIDIA_VISIBLE_DEVICES=void
  - NCCL_SOCKET_IFNAME=ens1f0np0
  - SGLANG_DISABLE_TP_MEMORY_INBALANCE_CHECK=1
```

---

### 问题五：SGLang FP8 block alignment 报错（最终切换 vLLM）

**现象**（使用 SGLang 后端时）：`ValueError: The output_size of gate's and up's weight = 192 is not divisible by weight quantization block_n = 128`

**根因**：MiniMax-M2.5 模型内置 FP8 block 量化（`weight_block_size=[128,128]`），MoE expert 的 `intermediate_size=1536`，TP=8 时每卡得到 `1536/8=192`，而 `192 % 128 ≠ 0`，SGLang 的 `fp8.py` 硬报错。

**解法**：在 gpustack 网页 UI 中将推理后端切换为 **vLLM**，vLLM 的 `--enable-expert-parallel` 以 Expert Parallelism 方式处理 MoE 分片，不存在此 alignment 问题。

同时需要添加：
```
--gpu-memory-utilization 0.85
```
（因为同机还有其他模型占用约 6 GB 显存，默认 0.9 阈值会触发内存不足报错）

---

### 最终 gpustack-worker 启动命令

```bash
docker run -d --name gpustack-worker --restart unless-stopped --privileged --network host \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v gpustack-data:/var/lib/gpustack \
  -v /usr/local/PPU_SDK:/usr/local/PPU_SDK:ro \
  -v /var/run/cdi:/var/run/cdi \
  -e GPUSTACK_TOKEN=<token> \
  -e GPUSTACK_RUNTIME_DOCKER_CDI_SPECS_GENERATE=false \
  -e GPUSTACK_RUNTIME_DOCKER_RESOURCE_INJECTION_POLICY=CDI \
  -e GPUSTACK_RUNTIME_DEPLOY_CDI_SPECS_DIRECTORY=/var/run/cdi \
  -e GPUSTACK_RUNTIME_DEPLOY_MIRRORED_DEPLOYMENT=true \
  -e GPUSTACK_RUNTIME_DEPLOY_MIRRORED_NAME=gpustack-worker \
  -e 'GPUSTACK_RUNTIME_DEPLOY_BACKEND_VISIBLE_DEVICES_VALUE_ALIGNMENT=ASCEND_RT_VISIBLE_DEVICES,NPU_VISIBLE_DEVICES,CUDA_VISIBLE_DEVICES' \
  -e NCCL_SOCKET_IFNAME=ens1f0np0 \
  docker.1ms.run/gpustack/gpustack \
  --server-url http://<server-ip> --worker-ip <worker-ip>
```

希望对遇到同样问题的同学有帮助。

---
## The problem has been solved and the complete troubleshooting process is recorded for reference.

**Environment**: Server 10.20.32.218, 8 PPUs (Alibaba Cloud Pingtou Ge), deploy MiniMax-M2.5 model

---

### Problem 1: CDI device driver cannot be selected

Original error: `could not select device driver "cdi" with capabilities: []`

**Reason**: The Docker version is older and does not natively support CDI.

**Solution**: Set environment variables in the gpustack-worker container, and let gpustack_runtime implement the CDI injection logic by itself, bypassing Docker's native CDI:
```
GPUSTACK_RUNTIME_DOCKER_RESOURCE_INJECTION_POLICY=CDI
GPUSTACK_RUNTIME_DOCKER_CDI_SPECS_GENERATE=false # Disable workers from overwriting manually maintained CDI specs
GPUSTACK_RUNTIME_DEPLOY_CDI_SPECS_DIRECTORY=/var/run/cdi
```

---

### Problem 2: CDI spec is missing ppu0 device entry (HGML index offset)

**Phenomena**: Container creation failed, the device with UUID `GPU-019ec20c-...` cannot be found in the CDI spec.

**Root cause**: HGML (`hgmlDeviceGetMinorNumber()`) returns the hardware minor number based on the PCI enumeration order (1~8 on this machine), not the order of Linux device files (0~7). results in:
- HGML minor = **8** for ppu0 (not 0)
- gpustack_runtime uses HGML minor to construct the device path `/dev/alixpu_ppu8`, but the file does not exist
- There is no entry for index=8 in the CDI spec

**Solution**: Manually add entries for ppu0 in `/var/run/cdi/alibabacloud.com-ppu.yaml`:
```yaml
- name: '8' # HGML index
  containerEdits:
    deviceNodes:
    - path: /dev/alixpu_ppu0 # Actual device file (major: 237, minor: 1)
      Major: 237
      minor: 1
      ...
- name: GPU-019ec20c-07a2-0a14-0000-0000407f7b2e # The UUID entry also points to ppu0
  containerEdits:
    deviceNodes:
    - path: /dev/alixpu_ppu0
```

---

### Problem three: CUDA_VISIBLE_DEVICES value error leads to `invalid device ordinal`

**Phenomenon**: `torch.AcceleratorError: CUDA error: invalid device ordinal`, `CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7,8` is reported in the container.

**Root cause**: gpustack sets `CUDA_VISIBLE_DEVICES` with HGML minor number (1~8 on this machine) by default, but HGML in the container uses 0-based enumeration (0~7), causing index 8 to be out of bounds.

**Solution**: Add: to the gpustack-worker container:
```
GPUSTACK_RUNTIME_DEPLOY_BACKEND_VISIBLE_DEVICES_VALUE_ALIGNMENT=ASCEND_RT_VISIBLE_DEVICES,NPU_VISIBLE_DEVICES,CUDA_VISIBLE_DEVICES
```
This way gpustack will use sequential 0-based indexing (`0,1,2,3,4,5,6,7`) instead of HGML minor numbers.

---

### Question 4: NCCL cannot find the network interface

**Phenomenon**: `NCCL ERROR Bootstrap: no socket interface found`

**Root cause**: `NCCL_SOCKET_IFNAME=eth0` is hard-coded in the inference image, but the host network card is `ens1f0np0`, and the workload configuration delivered by the gpustack server also contains `eth0`, so the mirrored deployment cannot overwrite it.

**Solution**: Inject in the CDI spec global `containerEdits.env`, the CDI env priority is higher than the container configuration:
```yaml
# /var/run/cdi/alibabacloud.com-ppu.yaml
containerEdits:
  env:
  - NVIDIA_VISIBLE_DEVICES=void
  - NCCL_SOCKET_IFNAME=ens1f0np0
  - SGLANG_DISABLE_TP_MEMORY_INBALANCE_CHECK=1
```

---

### Question 5: SGLang FP8 block alignment error (final switch to vLLM)

**Phenomena** (when using SGLang backend): `ValueError: The output_size of gate's and up's weight = 192 is not divisible by weight quantization block_n = 128`

**Root cause**: MiniMax-M2.5 model has built-in FP8 block quantization (`weight_block_size=[128,128]`), MoE expert's `intermediate_size=1536`, when TP=8, each card gets `1536/8=192`, and `192 % 128 ≠ 0`, SGLang's `fp8.py` Hard error.

**Solution**: Switch the inference backend to **vLLM** in the gpustack web UI. vLLM's `--enable-expert-parallel` handles MoE shards in Expert Parallelism, and this alignment problem does not exist.

Also need to add:
```
--gpu-memory-utilization 0.85
```
(Because there are other models on the same machine that occupy about 6 GB of video memory, the default 0.9 threshold will trigger an insufficient memory error)

---

### Final gpustack-worker startup command

```bash
docker run -d --name gpustack-worker --restart unless-stopped --privileged --network host \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v gpustack-data:/var/lib/gpustack \
  -v /usr/local/PPU_SDK:/usr/local/PPU_SDK:ro \
  -v /var/run/cdi:/var/run/cdi \
  -e GPUSTACK_TOKEN=<token> \
  -e GPUSTACK_RUNTIME_DOCKER_CDI_SPECS_GENERATE=false \
  -e GPUSTACK_RUNTIME_DOCKER_RESOURCE_INJECTION_POLICY=CDI \
  -e GPUSTACK_RUNTIME_DEPLOY_CDI_SPECS_DIRECTORY=/var/run/cdi \
  -e GPUSTACK_RUNTIME_DEPLOY_MIRRORED_DEPLOYMENT=true \
  -e GPUSTACK_RUNTIME_DEPLOY_MIRRORED_NAME=gpustack-worker \
  -e 'GPUSTACK_RUNTIME_DEPLOY_BACKEND_VISIBLE_DEVICES_VALUE_ALIGNMENT=ASCEND_RT_VISIBLE_DEVICES,NPU_VISIBLE_DEVICES,CUDA_VISIBLE_DEVICES' \
  -e NCCL_SOCKET_IFNAME=ens1f0np0 \
  docker.1ms.run/gpustack/gpustack \
  --server-url http://<server-ip> --worker-ip <worker-ip>
```

Hope it helps students who encounter the same problem.

**Comment by thxCode** [comment]
@fq393, great troubleshooting. 
1. Within your case, is the `8` minor device (returns by `hgmlDeviceGetMinorNumber`) using `/dev/alixpu_ppu0` device char? You can try with `--env GPUSTACK_RUNTIME_DETECT_PHYSICAL_INDEX_PRIORITY=0`, which will disable relying on the minor number. 
2. With `#1`, the `invalid device ordinal` will be gone, I think.
3. It's recommended to configure `NCCL_SOCKET_IFNAME` during model instance deployment, unless there is only one socket iface here.

**Comment by Vinobugme** [comment]
@fq393 hello大神，能否分享下您的PPU_SDK

---
@fq393 Hello Master, can you share your PPU_SDK

**Comment by fq393** [comment]
> [@fq393](https://github.com/fq393) hello大神，能否分享下您的PPU_SDK
> 
> [@fq393](https://github.com/fq393) Hello Master, can you share your PPU_SDK

用的是0.12.0 内置的hggc，没有SDK

---
> [@fq393](https://github.com/fq393) hello master, can you share your PPU_SDK
>
> [@fq393](https://github.com/fq393) Hello Master, can you share your PPU_SDK

I am using the built-in hggc in 0.12.0 and there is no SDK
