### ISSUE TITLE
Error when using Huawei Ascend 910B and CANN

### ISSUE THREAD

**Issue by h34dw1nd** [gpustack/gpustack#755]
**Describe the bug**

I deployed Gpustack by Docker, when I Deploying a Local Path Model qwen2.5-0.5b-instruct-gguf On Huawei Ascend 910B NPU, it raised an Error.

The log:

```
2024-12-10T07:42:14+00:00 - gpustack.worker.backends.llama_box - INFO - Starting llama-box server
0.00.669.734 I 
0.00.669.740 I version: v0.0.90 (b8ca250)
0.00.669.741 I compiler: cc (Ubuntu 11.4.0-2ubuntu1~20.04) 11.4.0
0.00.669.741 I target: aarch64-linux-gnu
0.00.669.741 I vendor: 
0.00.669.743 I   - llama.cpp 7736837d (4274)
0.00.669.743 I   - stable-diffusion.cpp 1b3faeb (191)
0.00.669.794 I system_info: n_threads = 192 (n_threads_batch = 192) / 192 | CPU : NEON = 1 | ARM_FMA = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | 
0.00.669.796 I 
0.00.669.893 I srv                      main: listening, hostname = 0.0.0.0, port = 40230, n_threads = 6 + 2
0.00.671.101 I srv                      main: loading model
0.00.671.120 I srv                load_model: loading model ''
0.00.671.417 I llama_load_model_from_file: using device CANN0 (Ascend910B2) - 62049 MiB free
0.00.722.758 I llama_model_loader: loaded meta data with 26 key-value pairs and 291 tensors from /data/qwen2.5-0.5b-instruct-guff/qwen2.5-0.5b-instruct-fp16.gguf (version GGUF V3 (latest))
0.00.722.775 I llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
0.00.722.780 I llama_model_loader: - kv   0:                       general.architecture str              = qwen2
0.00.722.781 I llama_model_loader: - kv   1:                               general.type str              = model
0.00.722.783 I llama_model_loader: - kv   2:                               general.name str              = qwen2.5-0.5b-instruct
0.00.722.784 I llama_model_loader: - kv   3:                            general.version str              = v0.1
0.00.722.785 I llama_model_loader: - kv   4:                           general.finetune str              = qwen2.5-0.5b-instruct
0.00.722.786 I llama_model_loader: - kv   5:                         general.size_label str              = 630M
0.00.722.789 I llama_model_loader: - kv   6:                          qwen2.block_count u32              = 24
0.00.722.790 I llama_model_loader: - kv   7:                       qwen2.context_length u32              = 8192
0.00.722.792 I llama_model_loader: - kv   8:                     qwen2.embedding_length u32              = 896
0.00.722.793 I llama_model_loader: - kv   9:                  qwen2.feed_forward_length u32              = 4864
0.00.722.794 I llama_model_loader: - kv  10:                 qwen2.attention.head_count u32              = 14
0.00.722.795 I llama_model_loader: - kv  11:              qwen2.attention.head_count_kv u32              = 2
0.00.722.808 I llama_model_loader: - kv  12:                       qwen2.rope.freq_base f32              = 1000000.000000
0.00.722.811 I llama_model_loader: - kv  13:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
0.00.722.812 I llama_model_loader: - kv  14:                          general.file_type u32              = 1
0.00.722.813 I llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
0.00.722.815 I llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = qwen2
0.00.751.163 I llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
0.00.758.011 I llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
0.00.786.350 I llama_model_loader: - kv  19:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
0.00.786.356 I llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151645
0.00.786.357 I llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
0.00.786.358 I llama_model_loader: - kv  22:                tokenizer.ggml.bos_token_id u32              = 151643
0.00.786.360 I llama_model_loader: - kv  23:               tokenizer.ggml.add_bos_token bool             = false
0.00.786.363 I llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
0.00.786.365 I llama_model_loader: - kv  25:               general.quantization_version u32              = 2
0.00.786.366 I llama_model_loader: - type  f32:  121 tensors
0.00.786.366 I llama_model_loader: - type  f16:  170 tensors
0.01.003.534 I llm_load_vocab: special tokens cache size = 22
0.01.077.060 I llm_load_vocab: token to piece cache size = 0.9310 MB
0.01.077.079 I llm_load_print_meta: format           = GGUF V3 (latest)
0.01.077.080 I llm_load_print_meta: arch             = qwen2
0.01.077.080 I llm_load_print_meta: vocab type       = BPE
0.01.077.081 I llm_load_print_meta: n_vocab          = 151936
0.01.077.082 I llm_load_print_meta: n_merges         = 151387
0.01.077.082 I llm_load_print_meta: vocab_only       = 0
0.01.077.083 I llm_load_print_meta: n_ctx_train      = 8192
0.01.077.083 I llm_load_print_meta: n_embd           = 896
0.01.077.084 I llm_load_print_meta: n_layer          = 24
0.01.077.098 I llm_load_print_meta: n_head           = 14
0.01.077.100 I llm_load_print_meta: n_head_kv        = 2
0.01.077.101 I llm_load_print_meta: n_rot            = 64
0.01.077.101 I llm_load_print_meta: n_swa            = 0
0.01.077.102 I llm_load_print_meta: n_embd_head_k    = 64
0.01.077.103 I llm_load_print_meta: n_embd_head_v    = 64
0.01.077.104 I llm_load_print_meta: n_gqa            = 7
0.01.077.106 I llm_load_print_meta: n_embd_k_gqa     = 128
0.01.077.108 I llm_load_print_meta: n_embd_v_gqa     = 128
0.01.077.110 I llm_load_print_meta: f_norm_eps       = 0.0e+00
0.01.077.111 I llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
0.01.077.113 I llm_load_print_meta: f_clamp_kqv      = 0.0e+00
0.01.077.114 I llm_load_print_meta: f_max_alibi_bias = 0.0e+00
0.01.077.115 I llm_load_print_meta: f_logit_scale    = 0.0e+00
0.01.077.116 I llm_load_print_meta: n_ff             = 4864
0.01.077.117 I llm_load_print_meta: n_expert         = 0
0.01.077.118 I llm_load_print_meta: n_expert_used    = 0
0.01.077.118 I llm_load_print_meta: causal attn      = 1
0.01.077.119 I llm_load_print_meta: pooling type     = 0
0.01.077.119 I llm_load_print_meta: rope type        = 2
0.01.077.120 I llm_load_print_meta: rope scaling     = linear
0.01.077.123 I llm_load_print_meta: freq_base_train  = 1000000.0
0.01.077.124 I llm_load_print_meta: freq_scale_train = 1
0.01.077.125 I llm_load_print_meta: n_ctx_orig_yarn  = 8192
0.01.077.125 I llm_load_print_meta: rope_finetuned   = unknown
0.01.077.126 I llm_load_print_meta: ssm_d_conv       = 0
0.01.077.126 I llm_load_print_meta: ssm_d_inner      = 0
0.01.077.127 I llm_load_print_meta: ssm_d_state      = 0
0.01.077.128 I llm_load_print_meta: ssm_dt_rank      = 0
0.01.077.131 I llm_load_print_meta: ssm_dt_b_c_rms   = 0
0.01.077.132 I llm_load_print_meta: model type       = 1B
0.01.077.134 I llm_load_print_meta: model ftype      = F16
0.01.077.136 I llm_load_print_meta: model params     = 630.17 M
0.01.077.138 I llm_load_print_meta: model size       = 1.17 GiB (16.00 BPW) 
0.01.077.139 I llm_load_print_meta: general.name     = qwen2.5-0.5b-instruct
0.01.077.140 I llm_load_print_meta: BOS token        = 151643 '<|endoftext|>'
0.01.077.141 I llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
0.01.077.141 I llm_load_print_meta: EOT token        = 151645 '<|im_end|>'
0.01.077.142 I llm_load_print_meta: PAD token        = 151643 '<|endoftext|>'
0.01.077.143 I llm_load_print_meta: LF token         = 148848 'ÄĬ'
0.01.077.143 I llm_load_print_meta: FIM PRE token    = 151659 '<|fim_prefix|>'
0.01.077.144 I llm_load_print_meta: FIM SUF token    = 151661 '<|fim_suffix|>'
0.01.077.144 I llm_load_print_meta: FIM MID token    = 151660 '<|fim_middle|>'
0.01.077.145 I llm_load_print_meta: FIM PAD token    = 151662 '<|fim_pad|>'
0.01.077.146 I llm_load_print_meta: FIM REP token    = 151663 '<|repo_name|>'
0.01.077.146 I llm_load_print_meta: FIM SEP token    = 151664 '<|file_sep|>'
0.01.077.147 I llm_load_print_meta: EOG token        = 151643 '<|endoftext|>'
0.01.077.148 I llm_load_print_meta: EOG token        = 151645 '<|im_end|>'
0.01.077.148 I llm_load_print_meta: EOG token        = 151662 '<|fim_pad|>'
0.01.077.149 I llm_load_print_meta: EOG token        = 151663 '<|repo_name|>'
0.01.077.149 I llm_load_print_meta: EOG token        = 151664 '<|file_sep|>'
0.01.077.150 I llm_load_print_meta: max token length = 256
0.01.083.898 I llm_load_tensors: offloading 24 repeating layers to GPU
0.01.083.903 I llm_load_tensors: offloading output layer to GPU
0.01.083.903 I llm_load_tensors: offloaded 25/25 layers to GPU
0.01.083.908 I llm_load_tensors:    CANN_Host model buffer size =   259.66 MiB
0.01.083.910 I llm_load_tensors:        CANN0 model buffer size =   942.43 MiB
...........................................................
0.01.439.168 I llama_new_context_with_model: n_seq_max     = 4
0.01.439.174 I llama_new_context_with_model: n_ctx         = 8192
0.01.439.174 I llama_new_context_with_model: n_ctx_per_seq = 2048
0.01.439.175 I llama_new_context_with_model: n_batch       = 2048
0.01.439.175 I llama_new_context_with_model: n_ubatch      = 512
0.01.439.177 I llama_new_context_with_model: flash_attn    = 0
0.01.439.189 I llama_new_context_with_model: freq_base     = 1000000.0
0.01.439.190 I llama_new_context_with_model: freq_scale    = 1
0.01.439.191 W llama_new_context_with_model: n_ctx_per_seq (2048) < n_ctx_train (8192) -- the full capacity of the model will not be utilized
0.01.444.876 I llama_kv_cache_init:      CANN0 KV buffer size =    96.00 MiB
0.01.444.884 I llama_new_context_with_model: KV self size  =   96.00 MiB, K (f16):   48.00 MiB, V (f16):   48.00 MiB
0.01.444.923 I llama_new_context_with_model:  CANN_Host  output buffer size =     0.01 MiB
0.01.448.822 I llama_new_context_with_model:      CANN0 compute buffer size =   298.50 MiB
0.01.448.829 I llama_new_context_with_model:  CANN_Host compute buffer size =    17.76 MiB
0.01.448.831 I llama_new_context_with_model: graph nodes  = 846
0.01.448.831 I llama_new_context_with_model: graph splits = 2
0.01.448.834 W common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
/usr/local/python3.10/lib/python3.10/site-packages/gpustack/third_party/bin/llama-box/llama-box --host 0.0.0.0 --embeddings --gpu-layers 25 --parallel 4 --ctx-size 8192 --port 40230 --model /data/qwen2.5-0.5b-instruct-guff/qwen2.5-0.5b-instruct-fp16.gguf --no-mmap
0.01.964.249 E CANN error: E89999: Inner Error!
E89999: [PID: 3860] 2024-12-10-07:42:16.547.492 op[Range], outSize from framework (OFF) is 1, but outSize from tiling (OFT) is 32,which maybe calc OFF by double, but calc OFT by floatplease use float to calc OFF while you wanner input's dtype is float[FUNC:CalculateOutputNum][FILE:range.cc][LINE:113]
        TraceBack (most recent call last):
       op[Range], calculate output_total_num value fail.[FUNC:AppendTilingArgs][FILE:range.cc][LINE:182]
       op[Range], append tiling args fail.[FUNC:Tiling4Range][FILE:range.cc][LINE:255]
       Tiling failed
       Tiling Failed.
       Kernel Run failed. opType: 7, Range
       launch failed for Range, errno:561103.
0.01.964.256 E   current device: 0, in function aclnn_arange at /home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cann/aclnn_ops.cpp:300
0.01.964.257 E   aclnnArange(workspaceAddr, workspaceSize, executor, ctx.stream())
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp:63: CANN error
```

**Environment**

- GPUStack version: v0.4.0
- OS: official Docker image
- GPU: Huawei 910B
- CANN Version: Ascend CANN Toolkit 8.0.RC3

**Comment by linyinli** [comment]
@h34dw1nd Is your Ascend driver version 24.1 rc2?

**Comment by h34dw1nd** [comment]
> @h34dw1nd Is your Ascend driver version 24.1 rc2?

@linyinli 24.1 rc3

**Comment by h34dw1nd** [comment]
> @h34dw1nd Our image uses CANN 8.0.rc3.beta1, which corresponds to the Ascend driver 24.1 rc2. However, I couldn’t find the 24.1 rc3 driver on the Ascend community website ([link](https://www.hiascend.com/hardware/firmware-drivers/community?product=2&model=28&cann=All&driver=1.0.25.alpha)).
> 
> If downgrading the driver is not an option, consider using our Dockerfile as a reference to build a compatible image: [Dockerfile.npu](https://github.com/gpustack/gpustack/blob/main/Dockerfile.npu).

I’m sure that the driver version is 24.1 rc3 , probably it has not been released publicly at the community. Maybe could I send the driver install package to you?

**Comment by linyinli** [comment]
@h34dw1nd Sure, you can share the download link here. Thanks a lot!

**Comment by linyinli** [comment]
And have you already installed the Ascend-cann-kernels-910b_8.0.RC3_linux-aarch64.run package?

**Comment by h34dw1nd** [comment]
> And have you already installed the Ascend-cann-kernels-910b_8.0.RC3_linux-aarch64.run package?

@linyinli Yes

**Comment by h34dw1nd** [comment]
> @h34dw1nd Sure, you can share the download link here. Thanks a lot!

@linyinli →_→ can download from here: https://www.hiascend.com/hardware/firmware-drivers/community?product=4&model=26&cann=8.0.0.alpha002&driver=1.0.27.alpha
Just choose Ascend-hdk-910b-npu-driver_24.1.rc3_linux-aarch64.run

**Comment by linyinli** [comment]
We’re currently facing a hardware issue with our 910B environment and need some time to resolve it. Previously, we validated CANN 8.0 RC3.beta1 with driver 24.1 rc2, if convenient, you might also try this version to see if it works.

**Comment by linyinli** [comment]
@h34dw1nd This issue has been solved in v0.5, If it still exists, reopen it.
